-- =====================================================================
-- 01_ddl.sql — DDL do modelo lógico v4 (tipos, domínios e 16 tabelas)
-- Banco de Dados II (CCO072) — IESB 2026/2
-- =====================================================================
-- Pré-condição: base `matricula` vazia (docker compose down -v && up -d).
-- Não é idempotente de propósito: reset = recriar a base.
--
-- Nomes:  tabela tb_<nome> · atributo <atributo>_<tabela> · PK id_<tabela>
--         FK = nome da PK referenciada · constraint pk_/uq_/ck_/fk_/ex_<tabela>_<assunto>
-- Colunas: PK → FK → texto → numéricos → demais (data, boolean, enum, jsonb)
-- Constraints: PK → UQ → CK → FK, dentro de cada CREATE TABLE.
-- FKs: ON UPDATE CASCADE sempre; ON DELETE RESTRICT, salvo onde comentado.
-- Tabelas em ordem de dependência: cada FK aponta para uma tabela já criada.

-- =====================================================================
-- PARTE 1 — EXTENSÃO, TIPOS E DOMÍNIOS
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;  -- '=' em colunas escalares no EXCLUDE de tb_turma_horario

-- Enums: a ordem dos rótulos é a ordem do ORDER BY.
CREATE TYPE tipo_sala_t  AS ENUM ('teorica', 'laboratorio', 'auditorio');
CREATE TYPE turno_t      AS ENUM ('matutino', 'vespertino', 'noturno');
CREATE TYPE vinculo_t    AS ENUM ('pre_requisito', 'co_requisito', 'equivalencia');
CREATE TYPE tipo_disc_t  AS ENUM ('obrigatoria', 'optativa', 'eletiva');
CREATE TYPE status_mat_t AS ENUM ('ativa', 'trancada', 'cancelada', 'concluida');
CREATE TYPE situacao_t   AS ENUM ('cursando', 'trancada', 'aprovado',
                                  'reprovado_nota', 'reprovado_falta', 'reprovado_nota_falta');

-- Domínios: o CHECK aceita NULL (nota não lançada não é violação).
CREATE DOMAIN nota_t AS numeric(4,2)        -- mesmo tipo de media_final_historico
    CONSTRAINT ck_nota_t_faixa CHECK (VALUE >= 0 AND VALUE <= 10);
CREATE DOMAIN pct_t  AS numeric(5,2)        -- (5,2) para caber 100,00
    CONSTRAINT ck_pct_t_faixa CHECK (VALUE >= 0 AND VALUE <= 100);

-- timerange não é nativo. A função de distância orienta o particionamento do GiST.
CREATE FUNCTION time_subtype_diff(x time, y time)
RETURNS float8
AS $$
    SELECT EXTRACT(EPOCH FROM (x - y))::float8;
$$ LANGUAGE sql IMMUTABLE STRICT;

CREATE TYPE timerange AS RANGE (
    subtype      = time,                    -- hora de parede, sem fuso
    subtype_diff = time_subtype_diff
);

COMMENT ON TYPE timerange IS
    'Faixa de horário de aula, sempre semiaberta [): 10:40 não conflita com 10:40.';

-- =====================================================================
-- PARTE 2 — TABELAS
-- =====================================================================

-- ---------------------------------------------------------------------
-- Nível 1: sem dependências
-- ---------------------------------------------------------------------

CREATE TABLE tb_campus (
    id_campus      smallint    GENERATED BY DEFAULT AS IDENTITY,
    nome_campus    varchar(60) NOT NULL,
    cidade_campus  varchar(60) NOT NULL,

    CONSTRAINT pk_campus PRIMARY KEY (id_campus),
    CONSTRAINT uq_campus_nome UNIQUE (nome_campus),
    CONSTRAINT ck_campus_nome_preenchido   CHECK (length(btrim(nome_campus)) > 0),
    CONSTRAINT ck_campus_cidade_preenchida CHECK (length(btrim(cidade_campus)) > 0)
);

CREATE TABLE tb_disciplina (
    id_disciplina          integer      GENERATED BY DEFAULT AS IDENTITY,
    codigo_disciplina      varchar(10)  NOT NULL,
    nome_disciplina        varchar(120) NOT NULL,
    ementa_disciplina      text,
    ch_teorica_disciplina  smallint     NOT NULL,
    ch_pratica_disciplina  smallint     NOT NULL,
    ch_total_disciplina    smallint     GENERATED ALWAYS AS
        (ch_teorica_disciplina + ch_pratica_disciplina) STORED,

    CONSTRAINT pk_disciplina PRIMARY KEY (id_disciplina),
    CONSTRAINT uq_disciplina_codigo UNIQUE (codigo_disciplina),
    CONSTRAINT ck_disciplina_codigo_preenchido CHECK (length(btrim(codigo_disciplina)) > 0),
    CONSTRAINT ck_disciplina_nome_preenchido   CHECK (length(btrim(nome_disciplina)) > 0),
    CONSTRAINT ck_disciplina_ch_nao_negativa                -- uma parcela pode ser 0...
        CHECK (ch_teorica_disciplina >= 0 AND ch_pratica_disciplina >= 0),
    CONSTRAINT ck_disciplina_ch_total_positiva              -- ...a soma não
        CHECK (ch_total_disciplina > 0)
);

CREATE TABLE tb_periodo_letivo (
    id_periodo_letivo           smallint GENERATED BY DEFAULT AS IDENTITY,  -- surrogate: não codifica ano/semestre
    ano_periodo_letivo          smallint NOT NULL,
    semestre_periodo_letivo     smallint NOT NULL,
    data_inicio_periodo_letivo  date     NOT NULL,
    data_fim_periodo_letivo     date     NOT NULL,

    CONSTRAINT pk_periodo_letivo PRIMARY KEY (id_periodo_letivo),
    CONSTRAINT uq_periodo_letivo_ano_semestre UNIQUE (ano_periodo_letivo, semestre_periodo_letivo),
    CONSTRAINT ck_periodo_letivo_semestre_valido CHECK (semestre_periodo_letivo IN (1, 2)),
    CONSTRAINT ck_periodo_letivo_ano_valido      CHECK (ano_periodo_letivo BETWEEN 2000 AND 2100),
    CONSTRAINT ck_periodo_letivo_intervalo
        CHECK (data_fim_periodo_letivo > data_inicio_periodo_letivo)
);

CREATE TABLE tb_professor (
    id_professor         integer      GENERATED BY DEFAULT AS IDENTITY,
    matricula_professor  varchar(12)  NOT NULL,
    nome_professor       varchar(120) NOT NULL,
    email_professor      varchar(120) NOT NULL,
    titulacao_professor  varchar(20),                     -- varchar, não enum: grafia varia nos dados

    CONSTRAINT pk_professor PRIMARY KEY (id_professor),
    CONSTRAINT uq_professor_matricula UNIQUE (matricula_professor),
    CONSTRAINT uq_professor_email     UNIQUE (email_professor),
    CONSTRAINT ck_professor_matricula_preenchida CHECK (length(btrim(matricula_professor)) > 0),
    CONSTRAINT ck_professor_nome_preenchido      CHECK (length(btrim(nome_professor)) > 0),
    CONSTRAINT ck_professor_email_minusculo                 -- torna a UQ de e-mail case-insensitive
        CHECK (email_professor = lower(email_professor)),
    CONSTRAINT ck_professor_email_formato        CHECK (email_professor LIKE '%_@_%._%')
);

-- ---------------------------------------------------------------------
-- Nível 2
-- ---------------------------------------------------------------------

CREATE TABLE tb_curso (
    id_curso        smallint     GENERATED BY DEFAULT AS IDENTITY,
    id_campus       smallint     NOT NULL,
    codigo_curso    varchar(10)  NOT NULL,
    nome_curso      varchar(120) NOT NULL,
    grau_curso      varchar(20),                          -- varchar, não enum: grafia varia nos dados
    ch_total_curso  smallint     NOT NULL,                -- valor oficial; não é gerada (dependeria de outras linhas)

    CONSTRAINT pk_curso PRIMARY KEY (id_curso),
    CONSTRAINT uq_curso_codigo UNIQUE (codigo_curso),
    CONSTRAINT ck_curso_codigo_preenchido CHECK (length(btrim(codigo_curso)) > 0),
    CONSTRAINT ck_curso_nome_preenchido   CHECK (length(btrim(nome_curso)) > 0),
    CONSTRAINT ck_curso_ch_total_positiva CHECK (ch_total_curso > 0),
    CONSTRAINT fk_curso_campus FOREIGN KEY (id_campus) REFERENCES tb_campus (id_campus)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE tb_sala (
    id_sala          integer     GENERATED BY DEFAULT AS IDENTITY,
    id_campus        smallint    NOT NULL,
    codigo_sala      varchar(10) NOT NULL,
    capacidade_sala  smallint    NOT NULL,
    tipo_sala        tipo_sala_t NOT NULL,

    CONSTRAINT pk_sala PRIMARY KEY (id_sala),
    CONSTRAINT uq_sala_campus_codigo UNIQUE (id_campus, codigo_sala),  -- código único por campus, não global
    CONSTRAINT ck_sala_codigo_preenchido CHECK (length(btrim(codigo_sala)) > 0),
    CONSTRAINT ck_sala_capacidade        CHECK (capacidade_sala BETWEEN 1 AND 1000),
    CONSTRAINT fk_sala_campus FOREIGN KEY (id_campus) REFERENCES tb_campus (id_campus)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE tb_feriado (
    id_feriado         integer      GENERATED BY DEFAULT AS IDENTITY,
    id_campus          smallint,                          -- NULL = feriado nacional
    descricao_feriado  varchar(120) NOT NULL,
    data_feriado       date         NOT NULL,

    CONSTRAINT pk_feriado PRIMARY KEY (id_feriado),
    CONSTRAINT uq_feriado_data_campus                       -- NULLS NOT DISTINCT: nacional não duplica na data
        UNIQUE NULLS NOT DISTINCT (data_feriado, id_campus),
    CONSTRAINT ck_feriado_descricao_preenchida CHECK (length(btrim(descricao_feriado)) > 0),
    CONSTRAINT fk_feriado_campus FOREIGN KEY (id_campus) REFERENCES tb_campus (id_campus)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE tb_turma (
    id_turma           integer     GENERATED BY DEFAULT AS IDENTITY,
    id_disciplina      integer     NOT NULL,
    id_periodo_letivo  smallint    NOT NULL,
    id_professor       integer     NOT NULL,
    codigo_turma       varchar(15) NOT NULL,
    vagas_turma        smallint    NOT NULL,              -- limite de matrículas: controlado por transação (Marco 2)
    turno_turma        turno_t     NOT NULL,

    CONSTRAINT pk_turma PRIMARY KEY (id_turma),
    CONSTRAINT uq_turma_periodo_codigo UNIQUE (id_periodo_letivo, codigo_turma),  -- código se repete a cada semestre
    CONSTRAINT uq_turma_id_periodo     UNIQUE (id_turma, id_periodo_letivo),      -- alvo da FK composta de tb_turma_horario
    CONSTRAINT ck_turma_codigo_preenchido CHECK (length(btrim(codigo_turma)) > 0),
    CONSTRAINT ck_turma_vagas             CHECK (vagas_turma BETWEEN 1 AND 300),
    CONSTRAINT fk_turma_disciplina FOREIGN KEY (id_disciplina)
        REFERENCES tb_disciplina (id_disciplina) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_turma_periodo_letivo FOREIGN KEY (id_periodo_letivo)
        REFERENCES tb_periodo_letivo (id_periodo_letivo) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_turma_professor FOREIGN KEY (id_professor)
        REFERENCES tb_professor (id_professor) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------
-- Nível 3
-- ---------------------------------------------------------------------

CREATE TABLE tb_curriculo (
    id_curriculo            integer  GENERATED BY DEFAULT AS IDENTITY,
    id_curso                smallint NOT NULL,
    ano_vigencia_curriculo  smallint NOT NULL,
    ativo_curriculo         boolean  NOT NULL DEFAULT true,

    CONSTRAINT pk_curriculo PRIMARY KEY (id_curriculo),
    CONSTRAINT uq_curriculo_curso_ano UNIQUE (id_curso, ano_vigencia_curriculo),
    CONSTRAINT uq_curriculo_id_curso  UNIQUE (id_curriculo, id_curso),  -- alvo da FK composta de tb_aluno
    CONSTRAINT ck_curriculo_ano_vigencia CHECK (ano_vigencia_curriculo BETWEEN 2000 AND 2100),
    CONSTRAINT fk_curriculo_curso FOREIGN KEY (id_curso) REFERENCES tb_curso (id_curso)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE tb_turma_horario (
    id_turma_horario          integer   GENERATED BY DEFAULT AS IDENTITY,
    id_turma                  integer   NOT NULL,
    id_periodo_letivo         smallint  NOT NULL,         -- cópia do período da turma, usada pelo EXCLUDE
    id_sala                   integer   NOT NULL,
    dia_semana_turma_horario  smallint  NOT NULL,         -- ISO: 1 = segunda ... 7 = domingo
    faixa_turma_horario       timerange NOT NULL,         -- sempre [)

    CONSTRAINT pk_turma_horario PRIMARY KEY (id_turma_horario),
    CONSTRAINT ck_turma_horario_dia_semana CHECK (dia_semana_turma_horario BETWEEN 1 AND 7),
    CONSTRAINT ck_turma_horario_faixa_valida                -- com início e fim, não vazia
        CHECK (NOT isempty(faixa_turma_horario)
           AND lower(faixa_turma_horario) IS NOT NULL
           AND upper(faixa_turma_horario) IS NOT NULL),
    CONSTRAINT ex_turma_horario_sala_ocupada                -- mesma sala, período e dia sem faixas sobrepostas
        EXCLUDE USING gist (
            id_sala                  WITH =,
            id_periodo_letivo        WITH =,
            dia_semana_turma_horario WITH =,
            faixa_turma_horario      WITH &&
        ),
    CONSTRAINT fk_turma_horario_turma                       -- composta: período tem de ser o da turma
        FOREIGN KEY (id_turma, id_periodo_letivo)
        REFERENCES tb_turma (id_turma, id_periodo_letivo)
        ON DELETE CASCADE ON UPDATE CASCADE,                -- horário é parte da turma
    CONSTRAINT fk_turma_horario_sala FOREIGN KEY (id_sala) REFERENCES tb_sala (id_sala)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------
-- Nível 4
-- ---------------------------------------------------------------------

CREATE TABLE tb_aluno (
    id_aluno          integer      GENERATED BY DEFAULT AS IDENTITY,
    id_curso          smallint     NOT NULL,
    id_curriculo      integer      NOT NULL,
    matricula_aluno   varchar(12)  NOT NULL,
    nome_aluno        varchar(120) NOT NULL,
    cpf_aluno         char(11)     NOT NULL,              -- só dígitos; DV é regra de aplicação
    email_aluno       varchar(120) NOT NULL,
    nascimento_aluno  date         NOT NULL,
    ingresso_aluno    date         NOT NULL,
    ativo_aluno       boolean      NOT NULL DEFAULT true, -- desligamento é false, nunca DELETE

    CONSTRAINT pk_aluno PRIMARY KEY (id_aluno),
    CONSTRAINT uq_aluno_matricula UNIQUE (matricula_aluno),
    CONSTRAINT uq_aluno_cpf       UNIQUE (cpf_aluno),
    CONSTRAINT uq_aluno_email     UNIQUE (email_aluno),
    CONSTRAINT ck_aluno_matricula_preenchida CHECK (length(btrim(matricula_aluno)) > 0),
    CONSTRAINT ck_aluno_nome_preenchido      CHECK (length(btrim(nome_aluno)) > 0),
    CONSTRAINT ck_aluno_cpf_valido           CHECK (cpf_aluno ~ '^[0-9]{11}$'),
    CONSTRAINT ck_aluno_email_minusculo      CHECK (email_aluno = lower(email_aluno)),
    CONSTRAINT ck_aluno_email_formato        CHECK (email_aluno LIKE '%_@_%._%'),
    CONSTRAINT ck_aluno_ingresso_apos_nascimento CHECK (ingresso_aluno > nascimento_aluno),
    CONSTRAINT ck_aluno_nascimento_plausivel
        CHECK (nascimento_aluno BETWEEN '1900-01-01' AND current_date),
    CONSTRAINT fk_aluno_curriculo_curso                     -- composta: currículo tem de ser do curso do aluno
        FOREIGN KEY (id_curriculo, id_curso)
        REFERENCES tb_curriculo (id_curriculo, id_curso)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_aluno_curso FOREIGN KEY (id_curso) REFERENCES tb_curso (id_curso)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE tb_curriculo_disciplina (
    id_curriculo                  integer     NOT NULL,
    id_disciplina                 integer     NOT NULL,
    periodo_curriculo_disciplina  smallint    NOT NULL,   -- semestre da grade (1º, 2º...), não o calendário
    tipo_curriculo_disciplina     tipo_disc_t NOT NULL,

    CONSTRAINT pk_curriculo_disciplina PRIMARY KEY (id_curriculo, id_disciplina),
    CONSTRAINT ck_curriculo_disciplina_periodo CHECK (periodo_curriculo_disciplina BETWEEN 1 AND 20),
    CONSTRAINT fk_curriculo_disciplina_curriculo FOREIGN KEY (id_curriculo)
        REFERENCES tb_curriculo (id_curriculo)
        ON DELETE CASCADE ON UPDATE CASCADE,                -- composição da grade
    CONSTRAINT fk_curriculo_disciplina_disciplina FOREIGN KEY (id_disciplina)
        REFERENCES tb_disciplina (id_disciplina)
        ON DELETE RESTRICT ON UPDATE CASCADE                -- catálogo compartilhado
);

-- ---------------------------------------------------------------------
-- Nível 5
-- ---------------------------------------------------------------------

CREATE TABLE tb_matricula (
    id_matricula      integer      GENERATED BY DEFAULT AS IDENTITY,
    id_aluno          integer      NOT NULL,
    id_turma          integer      NOT NULL,
    data_matricula    timestamptz  NOT NULL DEFAULT now(),
    status_matricula  status_mat_t NOT NULL,              -- trancar/cancelar muda status, não apaga

    CONSTRAINT pk_matricula PRIMARY KEY (id_matricula),
    CONSTRAINT uq_matricula_aluno_turma UNIQUE (id_aluno, id_turma),  -- sem duplicata na contagem de vagas
    CONSTRAINT ck_matricula_data_nao_futura CHECK (data_matricula <= now()),
    CONSTRAINT fk_matricula_aluno FOREIGN KEY (id_aluno) REFERENCES tb_aluno (id_aluno)
        ON DELETE RESTRICT ON UPDATE CASCADE,               -- preserva o registro acadêmico
    CONSTRAINT fk_matricula_turma FOREIGN KEY (id_turma) REFERENCES tb_turma (id_turma)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE tb_pre_requisito (
    id_curriculo             integer   NOT NULL,
    id_disciplina            integer   NOT NULL,          -- disciplina que exige
    id_disciplina_requisito  integer   NOT NULL,          -- disciplina exigida
    vinculo_pre_requisito    vinculo_t NOT NULL,

    CONSTRAINT pk_pre_requisito PRIMARY KEY (id_curriculo, id_disciplina, id_disciplina_requisito),
    CONSTRAINT ck_pre_requisito_sem_autorreferencia         -- barra A → A, não ciclos maiores
        CHECK (id_disciplina <> id_disciplina_requisito),
    CONSTRAINT fk_pre_requisito_disciplina                  -- composta: disciplina está na grade
        FOREIGN KEY (id_curriculo, id_disciplina)
        REFERENCES tb_curriculo_disciplina (id_curriculo, id_disciplina)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_pre_requisito_requisito                   -- composta: requisito na MESMA grade
        FOREIGN KEY (id_curriculo, id_disciplina_requisito)
        REFERENCES tb_curriculo_disciplina (id_curriculo, id_disciplina)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------
-- Nível 6
-- ---------------------------------------------------------------------

CREATE TABLE tb_historico (
    id_historico           integer    GENERATED BY DEFAULT AS IDENTITY,
    id_matricula           integer    NOT NULL,
    nota_a1_historico      nota_t,
    nota_a2_historico      nota_t,
    nota_p3_historico      nota_t,                        -- opcional: substitutiva
    frequencia_historico   pct_t,
    -- A1 40% + A2 60%; P3 substitui a menor e herda o peso; NULL sem A1 ou A2.
    media_final_historico  numeric(4,2) GENERATED ALWAYS AS (
        CASE
            WHEN nota_a1_historico IS NULL OR nota_a2_historico IS NULL
                THEN NULL                                   -- antes das comparações com NULL
            WHEN nota_p3_historico IS NULL
                THEN nota_a1_historico * 0.4 + nota_a2_historico * 0.6
            WHEN nota_a1_historico <= nota_a2_historico
                THEN nota_p3_historico * 0.4 + nota_a2_historico * 0.6
            ELSE nota_a1_historico * 0.4 + nota_p3_historico * 0.6
        END
    ) STORED,
    situacao_historico     situacao_t NOT NULL,

    CONSTRAINT pk_historico PRIMARY KEY (id_historico),
    CONSTRAINT uq_historico_matricula UNIQUE (id_matricula),  -- 1:1 com matrícula
    CONSTRAINT fk_historico_matricula FOREIGN KEY (id_matricula)
        REFERENCES tb_matricula (id_matricula)
        ON DELETE CASCADE ON UPDATE CASCADE                 -- notas não existem sem a matrícula
);

CREATE TABLE tb_log_matricula (
    id_log_matricula           bigint      GENERATED BY DEFAULT AS IDENTITY,  -- bigint: cresce por evento
    id_matricula               integer     NOT NULL,      -- sem FK: o log sobrevive ao DELETE
    acao_log_matricula         varchar(20) NOT NULL,      -- varchar, não enum: ações crescem
    usuario_log_matricula      name        NOT NULL DEFAULT current_user,
    ocorrido_em_log_matricula  timestamptz NOT NULL DEFAULT now(),
    detalhe_log_matricula      jsonb,

    CONSTRAINT pk_log_matricula PRIMARY KEY (id_log_matricula),
    CONSTRAINT ck_log_matricula_acao_preenchida CHECK (length(btrim(acao_log_matricula)) > 0),
    CONSTRAINT ck_log_matricula_detalhe_objeto
        CHECK (detalhe_log_matricula IS NULL OR jsonb_typeof(detalhe_log_matricula) = 'object')
);

-- =====================================================================
-- DOCUMENTAÇÃO NO CATÁLOGO (\dt+ no psql, aba Propriedades no pgAdmin)
-- =====================================================================

COMMENT ON TABLE tb_campus               IS 'Unidades físicas da instituição.';

COMMENT ON TABLE tb_disciplina           IS 'Catálogo de disciplinas, independente de curso.';
COMMENT ON TABLE tb_periodo_letivo       IS 'Semestres letivos do calendário.';
COMMENT ON TABLE tb_professor            IS 'Corpo docente.';

COMMENT ON TABLE tb_curso                IS 'Cursos de graduação, cada um em um campus.';

COMMENT ON TABLE tb_sala                 IS 'Espaços físicos de um campus.';

COMMENT ON TABLE tb_feriado              IS 'Feriados nacionais (id_campus NULL) e locais.';

COMMENT ON TABLE tb_turma                IS 'Oferta de uma disciplina em um período letivo.';

COMMENT ON TABLE tb_curriculo            IS 'Grade curricular de um curso por ano de vigência.';

COMMENT ON TABLE tb_turma_horario        IS 'Horários de aula; o EXCLUDE 
impede choque de sala.';

COMMENT ON TABLE tb_aluno                IS 'Alunos, vinculados a curso e currículo coerentes.';

COMMENT ON TABLE tb_curriculo_disciplina IS 'Disciplinas que compõem cada grade.';

COMMENT ON TABLE tb_matricula            IS 'Vínculo aluno-turma.';

COMMENT ON TABLE tb_pre_requisito        IS 'Requisitos entre disciplinas, por currículo.';

COMMENT ON TABLE tb_historico            IS 'Notas e situação de cada matrícula (1:1).';

COMMENT ON TABLE tb_log_matricula        IS 'Auditoria de matrícula, sem FK de propósito.';
