-- =====================================================================
-- 02_tabelas.sql
-- CREATE TABLE das 16 tabelas do modelo, sem constraints (ficam em 03)
-- Frente: Modelagem Física e Desempenho
-- Banco de Dados II (CCO072) — IESB 2026/2
-- =====================================================================
--
-- TODO: criar as 16 tabelas na ordem de dependência de FK:
--   1. campus, disciplina, periodo_letivo, professor
--   2. curso, sala, feriado, pre_requisito, turma
--   3. curriculo, turma_horario
--   4. curriculo_disciplina, aluno
--   5. matricula
--   6. historico
--   7. log_matricula (a qualquer momento — sem FK no modelo)
--
-- Conferir cada nome de tabela/coluna contra o modelo lógico antes de escrever.

-- ============================================================
-- TABELA CAMPUS
-- ============================================================
-- Essa é a tabela raiz do modelo.
-- Ela representa os campi/unidades físicas da instituição.
--
-- Outras tabelas irão utilizar o "id" desta tabela como
-- chave estrangeira (FK), como:
--   - curso.campus_id
--   - sala.campus_id
--   - feriado.campus_id
--
-- Por isso, o campus não depende de nenhuma outra tabela.
-- ============================================================

CREATE TABLE campus (
    
    -- ID gerado automaticamente, mas permite valor manual na carga.
    id smallint GENERATED BY DEFAULT AS IDENTITY,

    -- Nome obrigatório e com no máximo 60 caracteres.
    nome varchar(60) NOT NULL,

    -- Cidade obrigatória e com no máximo 60 caracteres.
    cidade varchar(60) NOT NULL,

    -- Identificador único do campus.
    CONSTRAINT pk_campus PRIMARY KEY (id),

    -- Não permite dois campi com o mesmo nome.
    CONSTRAINT uq_campus_nome UNIQUE (nome),

    -- Impede nome vazio ou apenas com espaços.
    CONSTRAINT ck_campus_nome_preenchido 
        CHECK (length(btrim(nome)) > 0),

    -- Impede cidade vazia ou apenas com espaços.
    CONSTRAINT ck_campus_cidade_preenchida
        CHECK (length(btrim(cidade)) > 0)  
);

-- Documentação da tabela.
COMMENT ON TABLE campus IS
    'Unidades físicas do centro universitário. Raiz da hierarquia campus > sala.';

-- O UNIQUE diferencia maiúsculas e minúsculas.
COMMENT ON COLUMN campus.nome IS
    'Único e case-sensitive: "Asa Sul" e "asa sul" são considerados valores distintos. '
    'O UNIQUE garante a unicidade, mas não ignora maiúsculas e minúsculas. '
    'Assim, SELECT * FROM campus WHERE nome = ''asa sul'' não encontra "Asa Sul".';

-- ============================================================
-- DISCIPLINA
-- ============================================================

CREATE TABLE disciplina(

    -- ID gerado automaticamente, mas permite valor manual na carga.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Código obrigatório e com no máximo 10 caracteres.
    codigo varchar(10) NOT NULL,

    -- Nome obrigatório e com no máximo 120 caracteres.
    nome varchar(120) NOT NULL,

    -- Cargas horárias obrigatórias.
    ch_teorica smallint NOT NULL,
    ch_pratica smallint NOT NULL,

    -- Calcula automaticamente a carga horária total.
    -- Ex.: 40 horas teóricas + 20 práticas = 60 horas totais.
    ch_total smallint GENERATED ALWAYS AS (ch_teorica + ch_pratica) STORED,

    -- Ementa pode ser cadastrada posteriormente.
    ementa text,

    -- Identificador único da disciplina.
    CONSTRAINT pk_disciplina PRIMARY KEY (id),

    -- Não permite disciplinas com o mesmo código.
    CONSTRAINT uq_disciplina_codigo UNIQUE (codigo),

    -- Impede código vazio ou apenas com espaços.
    CONSTRAINT ck_disciplina_codigo_preenchido
        CHECK (length(btrim(codigo)) > 0),

    -- Impede nome vazio ou apenas com espaços.
    CONSTRAINT ck_disciplina_nome_preenchido
        CHECK (length(btrim(nome)) > 0),

    -- As cargas horárias não pode ser negativa.
    -- Permite uma delas ser 0, por exemplo, disciplina 100% teórica.
    -- Garante que as cargas individuais não sejam negativas.
    CONSTRAINT ck_disciplina_ch_nao_negativa
        CHECK (ch_teorica >= 0 AND ch_pratica >= 0),

    -- Garante que a carga horária total seja maior que zero.
    -- Ex.: 0 + 0 = 0 não é permitido.
    CONSTRAINT ck_disciplina_ch_total_positiva
        CHECK (ch_total > 0)
);


-- Documentação da tabela.
COMMENT ON TABLE disciplina IS
    'Catálogo de disciplinas. Independe de curso e currículo: o vínculo '
    'disciplina-currículo vive em curriculo_disciplina.';
COMMENT ON COLUMN disciplina.ch_total IS
    'Gerada STORED a partir das parcelas. Parcelas NOT NULL garantem que '
    'nunca resulte NULL; ck_disciplina_ch_total_positiva impede soma zero.';

-- ============================================================
-- PERIODO LETIVO
-- ============================================================

CREATE TABLE periodo_letivo(

    -- ID gerado automaticamente.
    -- Não representa ano/semestre, apenas identifica o período.
    id smallint GENERATED BY DEFAULT AS IDENTITY,

    -- Ano do período letivo.
    ano smallint NOT NULL,
    
    -- Semestre: 1 = primeiro semestre, 2 = segundo semestre.
    semestre smallint NOT NULL,

    -- Data de início e fim do período.
    data_inicio date NOT NULL,
    data_fim date NOT NULL,

    -- Identificador único do período.
    CONSTRAINT pk_periodo_letivo PRIMARY KEY (id),

    -- Não permite dois períodos com o mesmo ano e semestre.
    CONSTRAINT uq_periodo_letivo_ano_semestre UNIQUE (ano, semestre),

    -- Permite apenas o primeiro ou segundo semestre.
    CONSTRAINT ck_periodo_letivo_semestre_valido
        CHECK (semestre IN (1, 2)),

    -- Evita anos inválidos ou erros de digitação.
    CONSTRAINT ck_periodo_letivo_ano_valido
        CHECK (ano BETWEEN 2000 AND 2100),

    -- A data final deve ser posterior à data inicial.
    CONSTRAINT ck_periodo_letivo_intervalo
        CHECK (data_fim > data_inicio)    

);


COMMENT ON TABLE periodo_letivo IS
    'Semestres letivos. (ano, semestre) é a chave natural; id é surrogate.';
COMMENT ON COLUMN periodo_letivo.id IS
    'Surrogate deliberado. Não codifica ano/semestre para não acoplar '
    'identidade a dado de negócio.';


-- ============================================================
-- PROFESSOR
-- ============================================================

-- Tabela de referência dos professores.
-- A tabela turma usa professor.id como FK.
CREATE TABLE professor(

    -- ID gerado automaticamente, mas permite valor manual na carga.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Matrícula obrigatória e única.
    matricula varchar(12) NOT NULL,
    
    -- Nome obrigatório.
    nome varchar(120) NOT NULL,

    -- Email obrigatório e único.
    email varchar(120) NOT NULL,

    -- Titulação opcional, pois pode não estar cadastrada.
    titulacao varchar(20),
    
    -- Identificador único do professor.
    CONSTRAINT pk_professor PRIMARY KEY (id),

    -- Não permite dois professores com a mesma matrícula.
    CONSTRAINT uq_professor_matricula UNIQUE (matricula),

    -- Não permite dois professores com o mesmo email.
    CONSTRAINT uq_professor_email UNIQUE (email),

    -- Impede matrícula vazia ou apenas com espaços.
    CONSTRAINT ck_professor_matricula_preenchida
        CHECK (length(btrim(matricula)) > 0),

    -- Impede nome vazio ou apenas com espaços.
    CONSTRAINT ck_professor_nome_preenchido
        CHECK (length(btrim(nome)) > 0),

    -- Obriga o email a ser armazenado em letras minúsculas.
    -- Ex.: joao@email.com é válido; Joao@email.com não.
    CONSTRAINT ck_professor_email_minusculo
        CHECK (email = lower(email)),

    -- Validação básica do formato do email.
    -- Não é uma validação completa de RFC.
    CONSTRAINT ck_professor_email_formato
    CHECK (email LIKE '%_@_%._%')
);

COMMENT ON TABLE professor IS
    'Corpo docente. Referenciada por turma.professor_id.';
COMMENT ON COLUMN professor.email IS
    'Armazenado sempre em minúsculas (ck_professor_email_minusculo), o que '
    'torna a UNIQUE simples equivalente a uma UNIQUE case-insensitive.';
COMMENT ON COLUMN professor.titulacao IS
    'varchar por definição do modelo, não enum. Sem CHECK de domínio para '
    'não quebrar a carga com variações de grafia.';

-- ============================================================
-- Curso
-- ============================================================

-- Primeira tabela com dependência: exige que campus já exista.
-- Referenciada por curriculo.curso_id e aluno.curso_id.

CREATE TABLE curso(

    -- ID único, gerado automaticamente, mas permite valor manual
    -- quando necessário em cargas de dados.
    id smallint GENERATED BY DEFAULT AS IDENTITY,

    -- Código obrigatório e único do curso.
    codigo varchar(10) NOT NULL,

    -- Nome obrigatório do curso.
    nome varchar(120) NOT NULL,

    -- Grau do curso, como Bacharelado ou Tecnólogo.
    -- Opcional porque pode não estar cadastrado.
    -- varchar em vez de ENUM para permitir variações dos dados reais.
    grau varchar(20),

    -- Carga horária total do curso.
    -- É armazenada diretamente porque depende de outras linhas
    -- do currículo e, portanto, não pode ser uma coluna GENERATED.
    ch_total integer NOT NULL,
    
    -- Campus ao qual o curso pertence.
    -- Obrigatório e deve existir em campus.id.
    campus_id smallint NOT NULL,

    -- Identifica unicamente cada curso.
    CONSTRAINT pk_curso PRIMARY KEY (id),

    -- Não permite dois cursos com o mesmo código.
    CONSTRAINT uq_curso_codigo UNIQUE (codigo),

    -- Impede código vazio ou apenas com espaços.
    CONSTRAINT ck_curso_codigo_preenchido
        CHECK (length(btrim(codigo)) > 0),

    -- Impede nome vazio ou apenas com espaços.
    CONSTRAINT ck_curso_nome_preenchido
        CHECK (length(btrim(nome)) > 0),
        
    -- Garante que a carga horária seja maior que zero.
    CONSTRAINT ck_curso_ch_total_positiva
        CHECK (ch_total > 0),

    -- Relaciona o curso ao campus.
    -- RESTRICT impede apagar um campus que ainda possui cursos.
    -- CASCADE atualiza campus_id caso o id do campus seja alterado.
    CONSTRAINT fk_curso_campus 
        FOREIGN KEY (campus_id) REFERENCES campus (id) ON DELETE RESTRICT ON UPDATE CASCADE

);

COMMENT ON TABLE curso IS
    'Cursos de graduação. Pertence a um campus; agrupa currículos.';
COMMENT ON COLUMN curso.ch_total IS
    'Denormalizado: carga horária oficial do curso. Não é coluna gerada '
    'porque dependeria de curriculo_disciplina (outras linhas), o que '
    'coluna gerada não permite.';
COMMENT ON COLUMN curso.codigo IS
    'Único e case-sensitive, mesmo padrão de campus.nome: "ADS" e "ads" '
    'são valores distintos para o UNIQUE.';
COMMENT ON COLUMN curso.grau IS
    'varchar por definição do modelo, não enum. Sem CHECK de domínio para '
    'não quebrar a carga com variações de grafia — mesmo motivo de '
    'professor.titulacao.';



-- ============================================================
-- SALA
-- ============================================================

-- Tabela de referência das salas.
-- Cada sala pertence obrigatoriamente a um campus.
-- A tabela turma_horario utiliza sala.id como FK.

CREATE TABLE sala(

    -- ID único, gerado automaticamente, mas permite valor manual
    -- quando necessário em cargas de dados.
    -- Usa integer porque turma_horario.sala_id também é integer.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Campus ao qual a sala pertence.
    -- Obrigatório e deve existir em campus.id.
    campus_id smallint NOT NULL,

    -- Código da sala, como A-101 ou LAB-01.
    -- Obrigatório.
    codigo varchar(10) NOT NULL,

    -- Quantidade máxima de pessoas na sala.
    -- Obrigatória e validada abaixo entre 1 e 1000.
    capacidade smallint NOT NULL,

    -- Tipo da sala, definido pelo ENUM tipo_sala_t.
    tipo tipo_sala_t NOT NULL,

    -- Identifica unicamente cada sala.
    CONSTRAINT pk_sala PRIMARY KEY (id),

    -- Garante que o código seja único dentro de cada campus.
    -- O mesmo código pode existir em campi diferentes.
    -- Ex.: Campus 1 → A-101 | Campus 2 → A-101.
    CONSTRAINT uq_sala_campus_codigo 
        UNIQUE (campus_id, codigo),


    -- Impede código vazio ou apenas com espaços.
    CONSTRAINT ck_sala_codigo_preenchido
        CHECK (length(btrim(codigo)) > 0),

    -- Garante uma capacidade entre 1 e 1000 pessoas.
    -- Evita valores inválidos ou possíveis erros de digitação.
    CONSTRAINT ck_sala_capacidade
        CHECK (capacidade BETWEEN 1 AND 1000),

    -- Relaciona a sala ao campus.
    -- RESTRICT impede apagar um campus que ainda possui salas.
    -- CASCADE atualiza campus_id caso o id do campus seja alterado.
    CONSTRAINT fk_sala_campus
        FOREIGN KEY (campus_id) REFERENCES campus (id) 
        ON DELETE RESTRICT 
        ON UPDATE CASCADE

);

COMMENT ON TABLE sala IS
    'Espaços físicos. Referenciada por turma_horario, onde o EXCLUDE impede '
    'duas turmas na mesma sala em horários sobrepostos.';
COMMENT ON COLUMN sala.codigo IS
    'Único por campus, não globalmente: o mesmo código pode se repetir em '
    'campi diferentes (uq_sala_campus_codigo).';


-- ============================================================
-- FERIADO
-- ============================================================

-- Tabela de referência dos feriados.
-- Pode representar feriados nacionais ou específicos de um campus.
-- Depende de campus. Não é referenciada por ninguém — é tabela folha,
-- consumida por consultas de calendário (dias letivos efetivos de um período).

CREATE TABLE feriado(

    -- ID único, gerado automaticamente, mas permite valor manual
    -- quando necessário em cargas de dados.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Data do feriado Obrigatório.
    data date NOT NULL,

    -- Descrição do feriado.
    -- Obrigatória e validada para não ser vazia.
    descricao varchar(120) NOT NULL,

    -- Campus ao qual o feriado pertence.
    --
    -- NULL = feriado nacional, válido para todos os campi.
    -- Preenchido = feriado local, válido apenas para aquele campus.
    --
    -- É nullable justamente para permitir feriados nacionais sem
    -- precisar cadastrar uma linha para cada campus.
    campus_id smallint,


    -- Identifica unicamente cada feriado.
    CONSTRAINT pk_feriado PRIMARY KEY (id),

    -- Impede a mesma data para o mesmo campus.
    --
    -- NULLS NOT DISTINCT é importante porque faz NULL ser tratado
    -- como igual a outro NULL.
    --
    -- Assim, não é possível cadastrar duas vezes o mesmo feriado
    -- nacional na mesma data.
    --
    -- Exemplos:
    --   (21/04/2026, NULL) → pode existir apenas uma vez.
    --   (15/08/2026, 1)    → pode existir apenas uma vez no campus 1.
    --   (15/08/2026, 2)    → permitido, pois é outro campus.
    CONSTRAINT uq_feriado_data_campus 
        UNIQUE NULLS NOT DISTINCT (data, campus_id),

    -- Impede descrição vazia ou formada apenas por espaços.
    CONSTRAINT ck_feriado_descricao_preenchida
        CHECK (length(btrim(descricao)) > 0),

    -- Relaciona o feriado ao campus.
    -- Quando campus_id estiver preenchido, ele precisa existir
    -- em campus.id.
    -- RESTRICT impede apagar um campus que possui feriados locais.
    -- CASCADE atualiza campus_id caso o id do campus seja alterado.
    CONSTRAINT fk_feriado_campus
        FOREIGN KEY (campus_id) REFERENCES campus (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE

);


COMMENT ON TABLE feriado IS
    'Feriados que suspendem aula. Sem FK para periodo_letivo: a relação com '
    'o semestre é por intervalo de data, resolvida em consulta.';
COMMENT ON COLUMN feriado.campus_id IS
    'NULL = feriado nacional (todos os campi). Preenchido = feriado local '
    'daquele campus. A UNIQUE usa NULLS NOT DISTINCT para que a duplicata '
    'de feriado nacional na mesma data seja rejeitada.';

-- ============================================================
-- PRE_REQUISITO
-- ============================================================

-- Tabela associativa de pré-requisitos entre disciplinas.
-- É um auto-relacionamento N:N: uma disciplina pode exigir várias
-- disciplinas e também pode ser requisito de várias outras.

CREATE TABLE pre_requisito(
    -- Disciplina que possui o requisito, ou seja, a disciplina
    -- que vem depois na sequência.
    disciplina_id integer NOT NULL,

    -- Disciplina que está sendo exigida como requisito.
    requisito_id integer NOT NULL,

    -- Tipo do vínculo entre as disciplinas, definido pelo ENUM
    -- vinculo_t. Obrigatório para identificar a natureza da relação.
    vinculo vinculo_t NOT NULL,

    -- Chave primária composta pelo par de disciplinas.
    -- Impede que o mesmo relacionamento seja cadastrado duas vezes.
    -- Não é necessário criar um id separado.
    CONSTRAINT pk_pre_requisito 
        PRIMARY KEY (disciplina_id, requisito_id),

    -- Impede que uma disciplina seja requisito dela mesma.
    -- Ex.: Algoritmos I não pode exigir Algoritmos I.
    -- Não impede ciclos maiores, como A → B → A.
    CONSTRAINT ck_pre_requisito_sem_autorreferencia
        CHECK (disciplina_id <> requisito_id),

    -- Garante que a disciplina que possui o requisito exista.
    -- CASCADE: ao apagar essa disciplina, seus vínculos de
    -- pré-requisito também são removidos.
    CONSTRAINT fk_pre_requisito_disciplina
        FOREIGN KEY (disciplina_id) REFERENCES disciplina (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- Garante que a disciplina exigida exista.
    -- RESTRICT: impede apagar uma disciplina que ainda é
    -- utilizada como requisito por outra.
    CONSTRAINT fk_pre_requisito_requisito
        FOREIGN KEY (requisito_id) REFERENCES disciplina (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

COMMENT ON TABLE pre_requisito IS
    'Auto-relacionamento N:N de disciplina. Base da consulta recursiva da '
    'árvore de pré-requisitos. Ciclos maiores que 1 NÃO são impedidos por '
    'constraint — é limitação conceitual, não de sintaxe.';
COMMENT ON COLUMN pre_requisito.disciplina_id IS
    'Disciplina que exige. ON DELETE CASCADE: apagar a disciplina apaga suas '
    'exigências, que não fazem sentido sem ela.';
COMMENT ON COLUMN pre_requisito.requisito_id IS
    'Disciplina exigida. ON DELETE RESTRICT: apagá-la quebraria a grade de '
    'outras disciplinas silenciosamente.';

-- ============================================================
-- TURMA
-- ============================================================

-- Oferta concreta de uma disciplina em determinado período.
-- Depende de disciplina, periodo_letivo e professor.
-- É referenciada por turma_horario e matricula.

CREATE TABLE turma(

    -- ID único da turma, gerado automaticamente.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Código da turma.
    -- Obrigatório e deve ser único dentro do período letivo.
    codigo varchar(15) NOT NULL,

    -- Disciplina oferecida pela turma.
    -- Deve existir em disciplina.id.
    disciplina_id integer NOT NULL,

    -- Período letivo em que a turma é ofertada.
    -- Deve existir em periodo_letivo.id.
    periodo_letivo_id smallint NOT NULL,

    -- Professor responsável pela turma.
    -- É obrigatório porque os dados utilizados já possuem
    -- professor definido para todas as turmas.
    professor_id integer NOT NULL,

    -- Turno da turma, definido pelo ENUM turno_t.
    turno turno_t NOT NULL,


    -- Quantidade de vagas disponíveis na turma.
    -- O controle de matrículas é feito entre tabelas e,
    -- portanto, não pode ser garantido apenas por CHECK.
    vagas smallint NOT NULL,

    -- Identifica cada turma de forma única.
    CONSTRAINT pk_turma PRIMARY KEY (id),

    -- O código pode se repetir em períodos diferentes,
    -- mas não pode se repetir dentro do mesmo período.
    -- Ex.: CCODM2B pode existir em 2026/1 e 2026/2.
    CONSTRAINT uq_turma_periodo_codigo
        UNIQUE (periodo_letivo_id, codigo),

    -- Impede código vazio ou formado apenas por espaços.
    CONSTRAINT ck_turma_codigo_preenchido
        CHECK (length(btrim(codigo)) > 0),

    -- Garante pelo menos 1 vaga e limita a 300.
    CONSTRAINT ck_turma_vagas
        CHECK (vagas BETWEEN 1 AND 300),

    -- Relaciona a turma à disciplina.
    -- RESTRICT impede apagar uma disciplina que possui turmas.
    CONSTRAINT fk_turma_disciplina
        FOREIGN KEY (disciplina_id) REFERENCES disciplina (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    -- Relaciona a turma ao período letivo.
    -- RESTRICT impede apagar um período que possui turmas.
    CONSTRAINT fk_turma_periodo_letivo
        FOREIGN KEY (periodo_letivo_id) REFERENCES periodo_letivo (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    -- Relaciona a turma ao professor responsável.
    -- RESTRICT impede apagar um professor que possui turmas.
    CONSTRAINT fk_turma_professor
        FOREIGN KEY (professor_id) REFERENCES professor (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE

);

COMMENT ON TABLE turma IS
    'Oferta de disciplina em um período letivo. Tabela central do Marco 2: '
    'vagas é o recurso disputado na anomalia de concorrência.';
COMMENT ON COLUMN turma.vagas IS
    'Capacidade ofertada. A regra COUNT(matricula) <= vagas NÃO é garantida '
    'por constraint — depende de outra tabela. É resolvida por transação '
    'com bloqueio explícito ou nível de isolamento adequado (Marco 2).';
COMMENT ON COLUMN turma.codigo IS
    'Único por período letivo, não globalmente: o mesmo código se repete a '
    'cada semestre (uq_turma_periodo_codigo).';

-- ============================================================
-- CURRICULO
-- ============================================================

-- Grade curricular de um curso, com ano de vigência.
-- Depende de curso. Referenciada por curriculo_disciplina.curriculo_id
-- e por aluno (curso_id, curriculo_id).

CREATE TABLE curriculo (
    
    -- ID único do currículo, gerado automaticamente.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Curso ao qual o currículo pertence.
    -- Deve existir em curso.id.
    curso_id smallint NOT NULL,

    -- Ano em que o currículo entrou em vigência.
    ano_vigencia smallint NOT NULL,

    -- Indica se o currículo está ativo.
    -- Novos currículos são criados como ativos por padrão.
    ativo boolean NOT NULL DEFAULT true,

    -- Identifica cada currículo de forma única.
    CONSTRAINT pk_curriculo PRIMARY KEY (id),

    -- Um curso não pode possuir duas grades para o mesmo
    -- ano de vigência.
    CONSTRAINT uq_curriculo_curso_ano 
        UNIQUE (curso_id, ano_vigencia),

    -- Permite que (id, curso_id) seja utilizado como alvo
    -- de uma FK composta na tabela aluno.
    CONSTRAINT uq_curriculo_id_curso
        UNIQUE (id, curso_id),

    -- Limita o ano de vigência ao intervalo de 2000 a 2100.
    CONSTRAINT ck_curriculo_ano_vigencia
        CHECK (ano_vigencia BETWEEN 2000 AND 2100),

    -- Relaciona o currículo ao curso.
    -- RESTRICT impede apagar um curso que possui currículos.
    CONSTRAINT fk_curriculo_curso
        FOREIGN KEY (curso_id) REFERENCES curso (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE

);

COMMENT ON TABLE curriculo IS
    'Grades curriculares por curso e ano de vigência. Um curso acumula '
    'várias grades ao longo do tempo; alunos ficam vinculados à sua.';
COMMENT ON CONSTRAINT uq_curriculo_id_curso ON curriculo IS
    'Aparentemente redundante (id já é PK). Existe para servir de alvo à FK '
    'composta (curriculo_id, curso_id) de aluno, que garante coerência entre '
    'o curso do aluno e o curso do seu currículo. A ordem das colunas na FK '
    'precisa casar com a ordem desta UNIQUE (id, curso_id).';

-- ============================================================
-- TURMA_HORARIO
-- ============================================================

-- Horário de aula de uma turma, com dia, faixa de horário e sala.
-- Depende de turma e sala.

CREATE TABLE turma_horario(

    -- ID único do horário, gerado automaticamente.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Turma à qual o horário pertence.
    -- Deve existir em turma.id.
    turma_id integer NOT NULL,

    -- Sala onde a aula será realizada.
    -- Deve existir em sala.id.
    sala_id integer NOT NULL,

    -- Dia da semana no padrão ISO:
    -- 1 = segunda ... 7 = domingo.
    dia_semana smallint NOT NULL,

    -- Faixa de horário da aula.
    -- Utiliza o tipo timerange definido no projeto.
    faixa timerange NOT NULL, 

    -- Identifica cada horário de forma única.
    CONSTRAINT pk_turma_horario PRIMARY KEY (id),

    -- Garante que o dia da semana esteja entre 1 e 7.
    CONSTRAINT ck_turma_horario_dia_semana
        CHECK (dia_semana BETWEEN 1 AND 7),

    -- Garante que a faixa possua início e fim e não seja vazia.
    CONSTRAINT ck_turma_horario_faixa_valida
        CHECK (NOT isempty(faixa) 
        AND lower(faixa) IS NOT NULL
        AND upper(faixa) IS NOT NULL),

    -- Impede duas turmas na mesma sala, no mesmo dia,
    -- com horários sobrepostos.
    -- Utiliza btree_gist para permitir '=' em sala_id e dia_semana.
    CONSTRAINT ex_turma_horario_sala_ocupada
        EXCLUDE USING  gist (
            sala_id WITH =,
            dia_semana WITH =,
            faixa WITH &&
        ),

    -- Relaciona o horário à turma.
    -- CASCADE exclui os horários quando a turma é excluída.
    CONSTRAINT fk_turma_horario_turma
        FOREIGN KEY (turma_id) REFERENCES turma (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- Relaciona o horário à sala.
    -- RESTRICT impede apagar uma sala que possui horários.
    CONSTRAINT fk_turma_horario_sala
        FOREIGN KEY (sala_id) REFERENCES sala (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

COMMENT ON TABLE turma_horario IS
    'Grade de horários. O EXCLUDE impede duas turmas na mesma sala, no mesmo '
    'dia, em faixas sobrepostas — regra entre linhas, impossível via CHECK.';
COMMENT ON COLUMN turma_horario.faixa IS
    'timerange criado no 01_tipos_dominios.sql (não é tipo nativo). Usar '
    'sempre limite [) para que aulas contíguas não conflitem.';
COMMENT ON CONSTRAINT ex_turma_horario_sala_ocupada ON turma_horario IS
    'Escopo: sala. NÃO impede que a mesma turma tenha dois horários '
    'sobrepostos em salas diferentes, nem conflito de professor.';

-- ============================================================
-- CURRICULO_DISCIPLINA
-- ============================================================

-- Associativa N:N entre curriculo e disciplina: quais disciplinas compõem
-- uma grade, em que período, com que natureza.
-- Depende de curriculo e disciplina. Não é referenciada por ninguém.

CREATE TABLE curriculo_disciplina(
    curriculo_id integer NOT NULL,
    disciplina_id integer NOT NULL,

    -- Semestre da grade em que a disciplina é ofertada (1º período, 2º...).
    -- NÃO confundir com periodo_letivo, que é o semestre calendário.
    -- Nomes parecidos, conceitos distintos.
    periodo smallint NOT NULL,

    -- Enum do modelo: obrigatória, optativa, eletiva.
    tipo tipo_disc_t NOT NULL,

    -- PK composta é a própria unicidade: uma disciplina aparece no máximo
    -- uma vez por currículo. Sem surrogate — o modelo não dá, e o par já
    -- identifica a linha.
    CONSTRAINT pk_curriculo_disciplina 
        PRIMARY KEY (curriculo_id, disciplina_id),

    -- Grade de graduação vai até ~10 períodos. Teto folgado, piso rígido:
    -- período 0 ou negativo não existe.
    CONSTRAINT ck_curriculo_disciplina_periodo
        CHECK (periodo BETWEEN 1 AND 20),

    -- CASCADE: a linha é parte composicional do currículo. Apagar a grade
    -- apaga sua composição, que não significa nada isolada.
    CONSTRAINT fk_curriculo_disciplina_curriculo
        FOREIGN KEY (curriculo_id) REFERENCES curriculo (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    -- RESTRICT: disciplina é catálogo independente, compartilhado por várias
    -- grades. Apagá-la esvaziaria currículos silenciosamente.
    -- Mesma assimetria de pre_requisito: composição em cascata, catálogo restrito.
    CONSTRAINT fk_curriculo_disciplina_disciplina
        FOREIGN KEY (disciplina_id) REFERENCES disciplina (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

COMMENT ON TABLE curriculo_disciplina IS
    'Composição da grade curricular. Junto com pre_requisito, é a base da '
    'consulta recursiva das disciplinas que um aluno já pode cursar.';
COMMENT ON COLUMN curriculo_disciplina.periodo IS
    'Semestre da GRADE (1º, 2º...), não o periodo_letivo calendário.';

-- ============================================================
-- ALUNO 
-- ============================================================

CREATE TABLE aluno(
    -- ID único do aluno, gerado automaticamente.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Matrícula obrigatória e única.
    matricula varchar(12) NOT NULL,

    -- Nome obrigatório.
    nome varchar(120) NOT NULL,

    -- CPF obrigatório, com 11 dígitos.
    cpf char(11) NOT NULL,

    -- Email obrigatório e único.
    email varchar(120) NOT NULL,

    -- Data de nascimento do aluno. 
    nascimento date NOT NULL,

    -- Curso do aluno, que deve existir em curso.id.
    curso_id smallint NOT NULL,

    -- Currículo do aluno, que deve existir em curriculo.id.
    curriculo_id integer NOT NULL,

    -- Data de ingresso do aluno na instituição.
    ingresso date NOT NULL,

    -- Indica se o aluno está ativo ou inativo. Por padrão, novos alunos são ativos.
    ativo boolean NOT NULL DEFAULT true,

    -- Identifica cada aluno de forma única.
    CONSTRAINT pk_aluno PRIMARY KEY (id),

    -- Não permite dois alunos com a mesma matrícula.
    CONSTRAINT uq_aluno_matricula UNIQUE (matricula),

    -- Não permite dois alunos com o mesmo CPF.
    CONSTRAINT uq_aluno_cpf UNIQUE (cpf),

    -- Não permite dois alunos com o mesmo email.
    CONSTRAINT uq_aluno_email UNIQUE (email),

    -- Impede matrícula vazia ou apenas com espaços.
    CONSTRAINT ck_aluno_matricula_preenchida
        CHECK (length(btrim(matricula)) > 0),

    -- Impede nome vazio ou apenas com espaços.
    CONSTRAINT ck_aluno_nome_preenchido
        CHECK (length(btrim(nome)) > 0),

    -- Único CHECK de formato do projeto, e a exceção se justifica: CPF tem
    -- formato universalmente fixo (11 dígitos), ao contrário de codigo/
    -- matricula, onde regex quebraria a carga real. Não valida dígito
    -- verificador — isso é regra de aplicação, não de integridade estrutural.
    CONSTRAINT ck_aluno_cpf_valido
        CHECK (cpf ~ '^[0-9]{11}$'),

    -- Mesma política de professor: normaliza em vez de índice funcional.
    CONSTRAINT ck_aluno_email_minusculo
        CHECK (email = lower(email)),
    CONSTRAINT ck_aluno_email_formato
        CHECK (email LIKE '%_@_%._%'),

    -- CHECKs multi-coluna: enxergam a linha inteira.
    CONSTRAINT ck_aluno_ingresso_apos_nascimento
        CHECK (ingresso > nascimento),

    -- Piso defensivo contra digitação (1900) sem inventar idade mínima.
    CONSTRAINT ck_aluno_nascimento_plausivel
        CHECK (nascimento BETWEEN '1900-01-01' AND current_date),


    -- FK COMPOSTA — o ponto da tabela.
    -- As duas colunas isoladas seriam válidas independentemente: nada
    -- impediria aluno no curso de Computação com currículo de Direito.
    -- Esta FK exige que o PAR exista junto em curriculo, o que só é
    -- verdade se o currículo pertencer àquele curso.
    -- Só é declarável porque curriculo tem uq_curriculo_id_curso: FK exige
    -- PK ou UNIQUE cobrindo as colunas referenciadas.
    -- Substitui a FK simples para curriculo — declarar as duas seria redundante.
    CONSTRAINT fk_aluno_curriculo_curso
        FOREIGN KEY (curriculo_id, curso_id) REFERENCES curriculo (id, curso_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,


    -- FK simples para curso: NÃO é redundante com a composta. A composta
    -- garante coerência do par; esta garante que curso_id aponta para curso
    -- existente mesmo isoladamente, e é o que o modelo declara.
    CONSTRAINT fk_aluno_curso
        FOREIGN KEY (curso_id) REFERENCES curso (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

COMMENT ON TABLE aluno IS
    'Alunos matriculados. A FK composta (curriculo_id, curso_id) impede a '
    'incoerência entre o curso do aluno e o curso do seu currículo.';
COMMENT ON COLUMN aluno.cpf IS
    'char(11), somente dígitos, sem pontuação. Dígito verificador não é '
    'validado no banco — é regra de aplicação.';
COMMENT ON CONSTRAINT fk_aluno_curriculo_curso ON aluno IS
    'Depende de uq_curriculo_id_curso em curriculo. Se aquela UNIQUE for '
    'removida, esta FK deixa de ser declarável.';

-- ============================================================
-- MATRICULA
-- ============================================================

CREATE TABLE matricula(
    -- ID único da matrícula, gerado automaticamente.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Aluno que realizou a matrícula.
    -- Deve existir em aluno.id.
    aluno_id integer NOT NULL,

    -- Turma na qual o aluno se matriculou.
    -- Deve existir em turma.id.
    turma_id integer NOT NULL,

    -- DEFAULT now(): o instante da matrícula é o instante do INSERT.
    -- timestamptz e não timestamp — o modelo escolheu com fuso, e está certo:
    -- armazena em UTC e converte na leitura, então não quebra com horário
    -- de verão nem com cliente em outro fuso. 
    data_matricula  timestamptz   NOT NULL DEFAULT now(),

    status status_mat_t NOT NULL,


    -- Identifica cada matrícula de forma única.
    CONSTRAINT pk_matricula PRIMARY KEY (id),

    -- Impede que um mesmo aluno se matricule duas vezes na mesma turma.
    CONSTRAINT uq_matricula_aluno_turma 
        UNIQUE (aluno_id, turma_id),

    -- Matrícula com data futura é erro de carga ou de relógio.
    CONSTRAINT ck_matricula_data_nao_futura
        CHECK (data_matricula <= now()),

    -- CASCADE: a matrícula é parte composicional do aluno. Apagar o aluno
    -- apaga seus vínculos, que não significam nada isolados.
    CONSTRAINT fk_matricula_aluno
        FOREIGN KEY (aluno_id) REFERENCES aluno (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    
    -- RESTRICT: turma é recurso independente com alunos dentro. Apagá-la
    -- com matrículas ativas é erro de operação, não intenção.
    CONSTRAINT fk_matricula_turma
        FOREIGN KEY (turma_id) REFERENCES turma (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE

);


COMMENT ON TABLE matricula IS
    'Vínculo aluno-turma. uq_matricula_aluno_turma não consta do diagrama '
    'mas é indispensável: sem ela a contagem de vagas do Marco 2 é corrompida '
    'por duplicatas.';
COMMENT ON COLUMN matricula.status IS
    'Trancamento e cancelamento são mudanças de status, não DELETE. A linha '
    'permanece para preservar o histórico.';