-- =====================================================================
-- 02_tabelas.sql
-- CREATE TABLE das 16 tabelas do modelo, sem constraints (ficam em 03)
-- Frente: Modelagem Física e Desempenho
-- Banco de Dados II (CCO072) — IESB 2026/2
-- =====================================================================
--
-- TODO: criar as 16 tabelas na ordem de dependência de FK:
--   1. campus, disciplina, periodo_letivo, professor
--   2. curso, sala, feriado, pre_requisito, turma
--   3. curriculo, turma_horario
--   4. curriculo_disciplina, aluno
--   5. matricula
--   6. historico
--   7. log_matricula (a qualquer momento — sem FK no modelo)
--
-- Conferir cada nome de tabela/coluna contra o modelo lógico antes de escrever.

-- ============================================================
-- TABELA CAMPUS
-- ============================================================
-- Essa é a tabela raiz do modelo.
-- Ela representa os campi/unidades físicas da instituição.
--
-- Outras tabelas irão utilizar o "id" desta tabela como
-- chave estrangeira (FK), como:
--   - curso.campus_id
--   - sala.campus_id
--   - feriado.campus_id
--
-- Por isso, o campus não depende de nenhuma outra tabela.
-- ============================================================

CREATE TABLE campus (
    
    -- ID gerado automaticamente, mas permite valor manual na carga.
    id smallint GENERATED BY DEFAULT AS IDENTITY,

    -- Nome obrigatório e com no máximo 60 caracteres.
    nome varchar(60) NOT NULL,

    -- Cidade obrigatória e com no máximo 60 caracteres.
    cidade varchar(60) NOT NULL,

    -- Identificador único do campus.
    CONSTRAINT pk_campus PRIMARY KEY (id),

    -- Não permite dois campi com o mesmo nome.
    CONSTRAINT uq_campus_nome UNIQUE (nome),

    -- Impede nome vazio ou apenas com espaços.
    CONSTRAINT ck_campus_nome_preenchido 
        CHECK (length(btrim(nome)) > 0),

    -- Impede cidade vazia ou apenas com espaços.
    CONSTRAINT ck_campus_cidade_preenchida
        CHECK (length(btrim(cidade)) > 0)  
);

-- Documentação da tabela.
COMMENT ON TABLE campus IS
    'Unidades físicas do centro universitário. Raiz da hierarquia campus > sala.';

-- O UNIQUE diferencia maiúsculas e minúsculas.
COMMENT ON COLUMN campus.nome IS
    'Único e case-sensitive: "Asa Sul" e "asa sul" são considerados valores distintos. '
    'O UNIQUE garante a unicidade, mas não ignora maiúsculas e minúsculas. '
    'Assim, SELECT * FROM campus WHERE nome = ''asa sul'' não encontra "Asa Sul".';

-- ============================================================
-- DISCIPLINA
-- ============================================================

CREATE TABLE disciplina(

    -- ID gerado automaticamente, mas permite valor manual na carga.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Código obrigatório e com no máximo 10 caracteres.
    codigo varchar(10) NOT NULL,

    -- Nome obrigatório e com no máximo 120 caracteres.
    nome varchar(120) NOT NULL,

    -- Cargas horárias obrigatórias.
    ch_teorica smallint NOT NULL,
    ch_pratica smallint NOT NULL,

    -- Calcula automaticamente a carga horária total.
    -- Ex.: 40 horas teóricas + 20 práticas = 60 horas totais.
    ch_total smallint GENERATED ALWAYS AS (ch_teorica + ch_pratica) STORED,

    -- Ementa pode ser cadastrada posteriormente.
    ementa text,

    -- Identificador único do id da disciplina.
    CONSTRAINT pk_disciplina PRIMARY KEY (id),

    -- Não permite disciplinas com o mesmo código.
    CONSTRAINT uq_disciplina_codigo UNIQUE (codigo),

    -- Impede código vazio ou apenas com espaços.
    CONSTRAINT ck_disciplina_codigo_preenchido
        CHECK (length(btrim(codigo)) > 0),

    -- Impede nome vazio ou apenas com espaços.
    CONSTRAINT ck_disciplina_nome_preenchido
        CHECK (length(btrim(nome)) > 0),

    -- As cargas horárias não pode ser negativa.
    -- Permite uma delas ser 0, por exemplo, disciplina 100% teórica.
    -- Garante que as cargas individuais não sejam negativas.
    CONSTRAINT ck_disciplina_ch_nao_negativa
        CHECK (ch_teorica >= 0 AND ch_pratica >= 0),

    -- Garante que a carga horária total seja maior que zero.
    -- Ex.: 0 + 0 = 0 não é permitido.
    CONSTRAINT ck_disciplina_ch_total_positiva
        CHECK (ch_total > 0)
);


-- Documentação da tabela.
COMMENT ON TABLE disciplina IS
    'Catálogo de disciplinas. Independe de curso e currículo: o vínculo '
    'disciplina-currículo vive em curriculo_disciplina.';
COMMENT ON COLUMN disciplina.ch_total IS
    'Gerada STORED a partir das parcelas. Parcelas NOT NULL garantem que '
    'nunca resulte NULL; ck_disciplina_ch_total_positiva impede soma zero.';
