-- =====================================================================
-- 02_tabelas.sql
-- CREATE TABLE das 16 tabelas do modelo: colunas, tipos, NOT NULL,
-- DEFAULT e colunas geradas. Constraints nomeadas (PK, FK, UNIQUE, CHECK,
-- EXCLUDE) ficam em 03_constraints.sql, adicionadas via ALTER TABLE.
-- Frente: Modelagem Física e Desempenho
-- Banco de Dados II (CCO072) — IESB 2026/2
-- =====================================================================
--
-- Ordem das tabelas abaixo == ordem de dependência de FK, preservada
-- mesmo sem FK declarada aqui (facilita ler 02 e 03 lado a lado):
--   1. campus, disciplina, periodo_letivo, professor
--   2. curso, sala, feriado, pre_requisito, turma
--   3. curriculo, turma_horario
--   4. curriculo_disciplina, aluno
--   5. matricula
--   6. historico
--   7. log_matricula (a qualquer momento — sem FK no modelo)
--
-- Conferir cada nome de tabela/coluna contra o modelo lógico antes de escrever.

-- ============================================================
-- TABELA CAMPUS
-- ============================================================
-- Essa é a tabela raiz do modelo.
-- Ela representa os campi/unidades físicas da instituição.
--
-- Outras tabelas irão utilizar o "id" desta tabela como
-- chave estrangeira (FK), como:
--   - curso.campus_id
--   - sala.campus_id
--   - feriado.campus_id
--
-- Por isso, o campus não depende de nenhuma outra tabela.
-- ============================================================

CREATE TABLE campus (

    -- ID gerado automaticamente, mas permite valor manual na carga.
    id smallint GENERATED BY DEFAULT AS IDENTITY,

    -- Nome obrigatório e com no máximo 60 caracteres.
    nome varchar(60) NOT NULL,

    -- Cidade obrigatória e com no máximo 60 caracteres.
    cidade varchar(60) NOT NULL
);

-- Documentação da tabela.
COMMENT ON TABLE campus IS
    'Unidades físicas do centro universitário. Raiz da hierarquia campus > sala.';

-- O UNIQUE diferencia maiúsculas e minúsculas.
COMMENT ON COLUMN campus.nome IS
    'Único e case-sensitive: "Asa Sul" e "asa sul" são considerados valores distintos. '
    'O UNIQUE garante a unicidade, mas não ignora maiúsculas e minúsculas. '
    'Assim, SELECT * FROM campus WHERE nome = ''asa sul'' não encontra "Asa Sul".';

-- ============================================================
-- DISCIPLINA
-- ============================================================

CREATE TABLE disciplina(

    -- ID gerado automaticamente, mas permite valor manual na carga.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Código obrigatório e com no máximo 10 caracteres.
    codigo varchar(10) NOT NULL,

    -- Nome obrigatório e com no máximo 120 caracteres.
    nome varchar(120) NOT NULL,

    -- Cargas horárias obrigatórias.
    ch_teorica smallint NOT NULL,
    ch_pratica smallint NOT NULL,

    -- Calcula automaticamente a carga horária total.
    -- Ex.: 40 horas teóricas + 20 práticas = 60 horas totais.
    ch_total smallint GENERATED ALWAYS AS (ch_teorica + ch_pratica) STORED,

    -- Ementa pode ser cadastrada posteriormente.
    ementa text
);


-- Documentação da tabela.
COMMENT ON TABLE disciplina IS
    'Catálogo de disciplinas. Independe de curso e currículo: o vínculo '
    'disciplina-currículo vive em curriculo_disciplina.';
COMMENT ON COLUMN disciplina.ch_total IS
    'Gerada STORED a partir das parcelas. Parcelas NOT NULL garantem que '
    'nunca resulte NULL; ck_disciplina_ch_total_positiva (03) impede soma zero.';

-- ============================================================
-- PERIODO LETIVO
-- ============================================================

CREATE TABLE periodo_letivo(

    -- ID gerado automaticamente.
    -- Não representa ano/semestre, apenas identifica o período.
    id smallint GENERATED BY DEFAULT AS IDENTITY,

    -- Ano do período letivo.
    ano smallint NOT NULL,

    -- Semestre: 1 = primeiro semestre, 2 = segundo semestre.
    semestre smallint NOT NULL,

    -- Data de início e fim do período.
    data_inicio date NOT NULL,
    data_fim date NOT NULL
);


COMMENT ON TABLE periodo_letivo IS
    'Semestres letivos. (ano, semestre) é a chave natural; id é surrogate.';
COMMENT ON COLUMN periodo_letivo.id IS
    'Surrogate deliberado. Não codifica ano/semestre para não acoplar '
    'identidade a dado de negócio.';


-- ============================================================
-- PROFESSOR
-- ============================================================

-- Tabela de referência dos professores.
-- A tabela turma usa professor.id como FK.
CREATE TABLE professor(

    -- ID gerado automaticamente, mas permite valor manual na carga.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Matrícula obrigatória e única.
    matricula varchar(12) NOT NULL,

    -- Nome obrigatório.
    nome varchar(120) NOT NULL,

    -- Email obrigatório e único.
    email varchar(120) NOT NULL,

    -- Titulação opcional, pois pode não estar cadastrada.
    titulacao varchar(20)
);

COMMENT ON TABLE professor IS
    'Corpo docente. Referenciada por turma.professor_id.';
COMMENT ON COLUMN professor.email IS
    'Armazenado sempre em minúsculas (ck_professor_email_minusculo, 03), o que '
    'torna a UNIQUE simples equivalente a uma UNIQUE case-insensitive.';
COMMENT ON COLUMN professor.titulacao IS
    'varchar por definição do modelo, não enum. Sem CHECK de domínio para '
    'não quebrar a carga com variações de grafia.';

-- ============================================================
-- Curso
-- ============================================================

-- Primeira tabela com dependência: exige que campus já exista.
-- Referenciada por curriculo.curso_id e aluno.curso_id.

CREATE TABLE curso(

    -- ID único, gerado automaticamente, mas permite valor manual
    -- quando necessário em cargas de dados.
    id smallint GENERATED BY DEFAULT AS IDENTITY,

    -- Código obrigatório e único do curso.
    codigo varchar(10) NOT NULL,

    -- Nome obrigatório do curso.
    nome varchar(120) NOT NULL,

    -- Grau do curso, como Bacharelado ou Tecnólogo.
    -- Opcional porque pode não estar cadastrado.
    -- varchar em vez de ENUM para permitir variações dos dados reais.
    grau varchar(20),

    -- Carga horária total do curso.
    -- É armazenada diretamente porque depende de outras linhas
    -- do currículo e, portanto, não pode ser uma coluna GENERATED.
    ch_total integer NOT NULL,

    -- Campus ao qual o curso pertence.
    -- Obrigatório e deve existir em campus.id (fk_curso_campus, 03).
    campus_id smallint NOT NULL
);

COMMENT ON TABLE curso IS
    'Cursos de graduação. Pertence a um campus; agrupa currículos.';
COMMENT ON COLUMN curso.ch_total IS
    'Denormalizado: carga horária oficial do curso. Não é coluna gerada '
    'porque dependeria de curriculo_disciplina (outras linhas), o que '
    'coluna gerada não permite.';
COMMENT ON COLUMN curso.codigo IS
    'Único e case-sensitive, mesmo padrão de campus.nome: "ADS" e "ads" '
    'são valores distintos para o UNIQUE.';
COMMENT ON COLUMN curso.grau IS
    'varchar por definição do modelo, não enum. Sem CHECK de domínio para '
    'não quebrar a carga com variações de grafia — mesmo motivo de '
    'professor.titulacao.';



-- ============================================================
-- SALA
-- ============================================================

-- Tabela de referência das salas.
-- Cada sala pertence obrigatoriamente a um campus.
-- A tabela turma_horario utiliza sala.id como FK.

CREATE TABLE sala(

    -- ID único, gerado automaticamente, mas permite valor manual
    -- quando necessário em cargas de dados.
    -- Usa integer porque turma_horario.sala_id também é integer.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Campus ao qual a sala pertence.
    -- Obrigatório e deve existir em campus.id (fk_sala_campus, 03).
    campus_id smallint NOT NULL,

    -- Código da sala, como A-101 ou LAB-01.
    -- Obrigatório.
    codigo varchar(10) NOT NULL,

    -- Quantidade máxima de pessoas na sala.
    -- Obrigatória e validada em 03 entre 1 e 1000.
    capacidade smallint NOT NULL,

    -- Tipo da sala, definido pelo ENUM tipo_sala_t.
    tipo tipo_sala_t NOT NULL
);

COMMENT ON TABLE sala IS
    'Espaços físicos. Referenciada por turma_horario, onde o EXCLUDE (03) impede '
    'duas turmas na mesma sala em horários sobrepostos.';
COMMENT ON COLUMN sala.codigo IS
    'Único por campus, não globalmente: o mesmo código pode se repetir em '
    'campi diferentes (uq_sala_campus_codigo, 03).';


-- ============================================================
-- FERIADO
-- ============================================================

-- Tabela de referência dos feriados.
-- Pode representar feriados nacionais ou específicos de um campus.
-- Depende de campus. Não é referenciada por ninguém — é tabela folha,
-- consumida por consultas de calendário (dias letivos efetivos de um período).

CREATE TABLE feriado(

    -- ID único, gerado automaticamente, mas permite valor manual
    -- quando necessário em cargas de dados.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Data do feriado Obrigatório.
    data date NOT NULL,

    -- Descrição do feriado.
    -- Obrigatória e validada para não ser vazia.
    descricao varchar(120) NOT NULL,

    -- Campus ao qual o feriado pertence.
    --
    -- NULL = feriado nacional, válido para todos os campi.
    -- Preenchido = feriado local, válido apenas para aquele campus.
    --
    -- É nullable justamente para permitir feriados nacionais sem
    -- precisar cadastrar uma linha para cada campus.
    campus_id smallint
);


COMMENT ON TABLE feriado IS
    'Feriados que suspendem aula. Sem FK para periodo_letivo: a relação com '
    'o semestre é por intervalo de data, resolvida em consulta.';
COMMENT ON COLUMN feriado.campus_id IS
    'NULL = feriado nacional (todos os campi). Preenchido = feriado local '
    'daquele campus. A UNIQUE (03) usa NULLS NOT DISTINCT para que a duplicata '
    'de feriado nacional na mesma data seja rejeitada.';

-- ============================================================
-- PRE_REQUISITO
-- ============================================================

-- Tabela associativa de pré-requisitos entre disciplinas.
-- É um auto-relacionamento N:N: uma disciplina pode exigir várias
-- disciplinas e também pode ser requisito de várias outras.

CREATE TABLE pre_requisito(
    -- Disciplina que possui o requisito, ou seja, a disciplina
    -- que vem depois na sequência.
    disciplina_id integer NOT NULL,

    -- Disciplina que está sendo exigida como requisito.
    requisito_id integer NOT NULL,

    -- Tipo do vínculo entre as disciplinas, definido pelo ENUM
    -- vinculo_t. Obrigatório para identificar a natureza da relação.
    vinculo vinculo_t NOT NULL
);

COMMENT ON TABLE pre_requisito IS
    'Auto-relacionamento N:N de disciplina. Base da consulta recursiva da '
    'árvore de pré-requisitos. Ciclos maiores que 1 NÃO são impedidos por '
    'constraint — é limitação conceitual, não de sintaxe.';
COMMENT ON COLUMN pre_requisito.disciplina_id IS
    'Disciplina que exige. ON DELETE CASCADE (03): apagar a disciplina apaga suas '
    'exigências, que não fazem sentido sem ela.';
COMMENT ON COLUMN pre_requisito.requisito_id IS
    'Disciplina exigida. ON DELETE RESTRICT (03): apagá-la quebraria a grade de '
    'outras disciplinas silenciosamente.';

-- ============================================================
-- TURMA
-- ============================================================

-- Oferta concreta de uma disciplina em determinado período.
-- Depende de disciplina, periodo_letivo e professor.
-- É referenciada por turma_horario e matricula.

CREATE TABLE turma(

    -- ID único da turma, gerado automaticamente.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Código da turma.
    -- Obrigatório e deve ser único dentro do período letivo.
    codigo varchar(15) NOT NULL,

    -- Disciplina oferecida pela turma.
    -- Deve existir em disciplina.id.
    disciplina_id integer NOT NULL,

    -- Período letivo em que a turma é ofertada.
    -- Deve existir em periodo_letivo.id.
    periodo_letivo_id smallint NOT NULL,

    -- Professor responsável pela turma.
    -- É obrigatório porque os dados utilizados já possuem
    -- professor definido para todas as turmas.
    professor_id integer NOT NULL,

    -- Turno da turma, definido pelo ENUM turno_t.
    turno turno_t NOT NULL,


    -- Quantidade de vagas disponíveis na turma.
    -- O controle de matrículas é feito entre tabelas e,
    -- portanto, não pode ser garantido apenas por CHECK.
    vagas smallint NOT NULL
);

COMMENT ON TABLE turma IS
    'Oferta de disciplina em um período letivo. Tabela central do Marco 2: '
    'vagas é o recurso disputado na anomalia de concorrência.';
COMMENT ON COLUMN turma.vagas IS
    'Capacidade ofertada. A regra COUNT(matricula) <= vagas NÃO é garantida '
    'por constraint — depende de outra tabela. É resolvida por transação '
    'com bloqueio explícito ou nível de isolamento adequado (Marco 2).';
COMMENT ON COLUMN turma.codigo IS
    'Único por período letivo, não globalmente: o mesmo código se repete a '
    'cada semestre (uq_turma_periodo_codigo, 03).';

-- ============================================================
-- CURRICULO
-- ============================================================

-- Grade curricular de um curso, com ano de vigência.
-- Depende de curso. Referenciada por curriculo_disciplina.curriculo_id
-- e por aluno (curso_id, curriculo_id).

CREATE TABLE curriculo (

    -- ID único do currículo, gerado automaticamente.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Curso ao qual o currículo pertence.
    -- Deve existir em curso.id.
    curso_id smallint NOT NULL,

    -- Ano em que o currículo entrou em vigência.
    ano_vigencia smallint NOT NULL,

    -- Indica se o currículo está ativo.
    -- Novos currículos são criados como ativos por padrão.
    ativo boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE curriculo IS
    'Grades curriculares por curso e ano de vigência. Um curso acumula '
    'várias grades ao longo do tempo; alunos ficam vinculados à sua.';

-- ============================================================
-- TURMA_HORARIO
-- ============================================================

-- Horário de aula de uma turma, com dia, faixa de horário e sala.
-- Depende de turma e sala.

CREATE TABLE turma_horario(

    -- ID único do horário, gerado automaticamente.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Turma à qual o horário pertence.
    -- Deve existir em turma.id.
    turma_id integer NOT NULL,

    -- Sala onde a aula será realizada.
    -- Deve existir em sala.id.
    sala_id integer NOT NULL,

    -- Dia da semana no padrão ISO:
    -- 1 = segunda ... 7 = domingo.
    dia_semana smallint NOT NULL,

    -- Faixa de horário da aula.
    -- Utiliza o tipo timerange definido no projeto.
    faixa timerange NOT NULL
);

COMMENT ON TABLE turma_horario IS
    'Grade de horários. O EXCLUDE (03) impede duas turmas na mesma sala, no mesmo '
    'dia, em faixas sobrepostas — regra entre linhas, impossível via CHECK.';
COMMENT ON COLUMN turma_horario.faixa IS
    'timerange criado no 01_tipos_dominios.sql (não é tipo nativo). Usar '
    'sempre limite [) para que aulas contíguas não conflitem.';

-- ============================================================
-- CURRICULO_DISCIPLINA
-- ============================================================

-- Associativa N:N entre curriculo e disciplina: quais disciplinas compõem
-- uma grade, em que período, com que natureza.
-- Depende de curriculo e disciplina. Não é referenciada por ninguém.

CREATE TABLE curriculo_disciplina(
    curriculo_id integer NOT NULL,
    disciplina_id integer NOT NULL,

    -- Semestre da grade em que a disciplina é ofertada (1º período, 2º...).
    -- NÃO confundir com periodo_letivo, que é o semestre calendário.
    -- Nomes parecidos, conceitos distintos.
    periodo smallint NOT NULL,

    -- Enum do modelo: obrigatória, optativa, eletiva.
    tipo tipo_disc_t NOT NULL
);

COMMENT ON TABLE curriculo_disciplina IS
    'Composição da grade curricular. Junto com pre_requisito, é a base da '
    'consulta recursiva das disciplinas que um aluno já pode cursar.';
COMMENT ON COLUMN curriculo_disciplina.periodo IS
    'Semestre da GRADE (1º, 2º...), não o periodo_letivo calendário.';

-- ============================================================
-- ALUNO
-- ============================================================

CREATE TABLE aluno(
    -- ID único do aluno, gerado automaticamente.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Matrícula obrigatória e única.
    matricula varchar(12) NOT NULL,

    -- Nome obrigatório.
    nome varchar(120) NOT NULL,

    -- CPF obrigatório, com 11 dígitos.
    cpf char(11) NOT NULL,

    -- Email obrigatório e único.
    email varchar(120) NOT NULL,

    -- Data de nascimento do aluno.
    nascimento date NOT NULL,

    -- Curso do aluno, que deve existir em curso.id.
    curso_id smallint NOT NULL,

    -- Currículo do aluno, que deve existir em curriculo.id.
    curriculo_id integer NOT NULL,

    -- Data de ingresso do aluno na instituição.
    ingresso date NOT NULL,

    -- Indica se o aluno está ativo ou inativo. Por padrão, novos alunos são ativos.
    ativo boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE aluno IS
    'Alunos matriculados. A FK composta (curriculo_id, curso_id), em 03, impede a '
    'incoerência entre o curso do aluno e o curso do seu currículo.';
COMMENT ON COLUMN aluno.cpf IS
    'char(11), somente dígitos, sem pontuação. Dígito verificador não é '
    'validado no banco — é regra de aplicação.';

-- ============================================================
-- MATRICULA
-- ============================================================

CREATE TABLE matricula(
    -- ID único da matrícula, gerado automaticamente.
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- Aluno que realizou a matrícula.
    -- Deve existir em aluno.id.
    aluno_id integer NOT NULL,

    -- Turma na qual o aluno se matriculou.
    -- Deve existir em turma.id.
    turma_id integer NOT NULL,

    -- DEFAULT now(): o instante da matrícula é o instante do INSERT.
    -- timestamptz e não timestamp — o modelo escolheu com fuso, e está certo:
    -- armazena em UTC e converte na leitura, então não quebra com horário
    -- de verão nem com cliente em outro fuso.
    data_matricula  timestamptz   NOT NULL DEFAULT now(),

    status status_mat_t NOT NULL
);


COMMENT ON TABLE matricula IS
    'Vínculo aluno-turma. uq_matricula_aluno_turma (03) não consta do diagrama '
    'mas é indispensável: sem ela a contagem de vagas do Marco 2 é corrompida '
    'por duplicatas.';
COMMENT ON COLUMN matricula.status IS
    'Trancamento e cancelamento são mudanças de status, não DELETE. A linha '
    'permanece para preservar o histórico.';

-- ============================================================
-- HISTORICO
-- ============================================================

-- 1:1 com matricula: notas e situação final.
-- Depende de matricula. Não é referenciada por ninguém.
CREATE TABLE historico (
    id           integer      GENERATED BY DEFAULT AS IDENTITY,

    -- FK + UNIQUE = relação 1:1. O modelo marca FK,U explicitamente:
    -- uma matrícula tem no máximo um histórico. FK e UNIQUE ficam em 03.
    matricula_id integer      NOT NULL,

    -- Domínios do 01_tipos_dominios.sql. nota_t já carrega o CHECK de faixa
    -- (0 a 10), então não repito aqui — a validação vive no domínio, que é
    -- reaproveitado nas três colunas. É a vantagem de DOMAIN sobre CHECK
    -- repetido: uma definição, três usos.
    nota_a1      nota_t,
    nota_a2      nota_t,

    -- Nullable por natureza: a maioria dos alunos não faz P3.
    nota_p3      nota_t,

    frequencia   pct_t,

    situacao     situacao_t   NOT NULL,

    -- SEGUNDA COLUNA GERADA DO PROJETO. STORED (única opção no PG 17).
    -- Regra: A1 pesa 40%, A2 pesa 60%. Se houver P3, ele substitui a menor
    -- das duas notas, HERDANDO O PESO do slot que ocupa.
    -- Toda a lógica precisa caber numa expressão IMMUTABLE que só enxerga
    -- a própria linha — daí o CASE aninhado em vez de função.
    -- Se qualquer nota necessária for NULL, o resultado é NULL: aluno sem
    -- nota lançada não tem média, e isso é honesto (não vira zero).
    media_final  numeric(4,2) GENERATED ALWAYS AS (
    CASE
        -- GUARDA: média só existe com A1 e A2 lançadas. Precisa vir ANTES
        -- de qualquer comparação, porque comparar com NULL devolve NULL
        -- (desconhecido), e o ELSE captura falso e desconhecido no mesmo
        -- ramo — foi essa colisão que produzia média concreta com A2 nula.
        WHEN nota_a1 IS NULL OR nota_a2 IS NULL
            THEN NULL
        WHEN nota_p3 IS NULL
            THEN nota_a1 * 0.4 + nota_a2 * 0.6
        WHEN nota_a1 <= nota_a2
            THEN nota_p3 * 0.4 + nota_a2 * 0.6
        ELSE nota_a1 * 0.4 + nota_p3 * 0.6
    END
) STORED
);

COMMENT ON TABLE historico IS
    'Notas e situação por matrícula. Relação 1:1 garantida por '
    'uq_historico_matricula (03).';
COMMENT ON COLUMN historico.media_final IS
    'A1 40%, A2 60%. P3, quando presente, substitui a menor das duas e herda '
    'o peso do slot. NULL se faltar nota — ausência não é zero.';
COMMENT ON COLUMN historico.nota_p3 IS
    'Nullable por natureza: a maioria dos alunos não faz prova substitutiva.';



-- ============================================================
-- LOG_MATRICULA
-- ============================================================

-- Trilha de auditoria de matrícula. Independe de ordem de criação: não tem
-- FK nenhuma, pode ser criada a qualquer momento.
-- Alimentada por trigger no Marco 2, junto com a frente de transações.
CREATE TABLE log_matricula (
    -- bigint, não integer: única tabela do modelo com PK de 64 bits.
    -- Log cresce por EVENTO, não por entidade — uma matrícula gera N linhas
    -- (criação, trancamento, cancelamento). Volume de log é ordens de
    -- grandeza maior que o de dados.
    id           bigint       GENERATED BY DEFAULT AS IDENTITY,

    -- SEM FK — DELIBERADO, e é o ponto desta tabela.
    -- Se houvesse FK, apagar uma matrícula apagaria (CASCADE) ou impediria
    -- (RESTRICT) o registro do que aconteceu com ela. Nos dois casos a
    -- auditoria perde exatamente o evento mais interessante: a remoção.
    -- Log guarda FATO HISTÓRICO, não referência viva. O id é conservado
    -- mesmo depois da linha original deixar de existir.
    matricula_id integer      NOT NULL,

    -- varchar e não enum: o conjunto de ações cresce com o tempo, e enum
    -- não permite remover valor. Aqui a flexibilidade vale mais que a
    -- restrição — critério inverso ao de turno_t e status_mat_t, onde o
    -- domínio é fechado e estável.
    acao         varchar(20)  NOT NULL,

    ocorrido_em  timestamptz  NOT NULL DEFAULT now(),

    -- Tipo 'name' do próprio Postgres (63 bytes), o mesmo de current_user.
    -- O modelo escolheu por coerência com o catálogo do sistema.
    usuario      name         NOT NULL DEFAULT current_user,

    -- Payload flexível: guarda o antes/depois do evento sem exigir uma
    -- coluna por campo auditado. jsonb (binário, indexável, chaves únicas)
    -- e não json (texto puro, preserva formatação, mais lento pra consultar).
    detalhe      jsonb
);

COMMENT ON TABLE log_matricula IS
    'Auditoria de matrícula. Ausência de FK em matricula_id é deliberada: '
    'o log deve sobreviver à remoção da linha auditada.';
COMMENT ON COLUMN log_matricula.matricula_id IS
    'Referência histórica, não FK. Pode apontar para matrícula já removida — '
    'é justamente o caso que a auditoria precisa registrar.';
COMMENT ON COLUMN log_matricula.detalhe IS
    'jsonb com o contexto do evento (estado anterior, novo status, origem). '
    'Estrutura livre por design: cada ação registra o que lhe é relevante.';
