-- =====================================================================
-- 04_carga.sql
-- Carga de dados: grade real de Ciência da Computação (2023/1) e de
-- Engenharia de Computação, mais alunos, matrículas e histórico gerados
-- com generate_series (mínimo: 100 alunos, 6 turmas, 300 matrículas).
-- Frente: Modelagem Física e Desempenho
-- Banco de Dados II (CCO072) — IESB 2026/2
-- =====================================================================
--
-- Pré-condição: 01, 02 e 03 já rodados, banco vazio.
--
-- Decisões da carga:
--
-- 1. Um módulo por semestre. Os dois cursos têm 8 módulos (1A..4B), um por
--    semestre. Com os 4 períodos carregados, 2026/2 é o módulo 2B:
--        2025/1 -> 1A (periodo 1)    2025/2 -> 1B (periodo 2)
--        2026/1 -> 2A (periodo 3)    2026/2 -> 2B (periodo 4, em andamento)
--    periodo_curriculo_disciplina guarda esse número (1 a 8).
--
-- 2. Tudo é determinístico: sem random(). Rodar a carga duas vezes em bancos
--    limpos gera o mesmo banco, o que permite comparar EXPLAIN antes e
--    depois dos índices.
--
-- 3. Sem ids explícitos: as colunas são GENERATED BY DEFAULT, e inserir um id
--    na mão não avança a sequence. Todas as FKs são resolvidas por chave
--    natural (nome, código, matrícula) via JOIN.
--
-- 4. Dados fictícios: professores e alunos são inventados. Disciplinas,
--    módulos e cargas horárias seguem as grades; onde a grade só informa o
--    total do módulo, a carga foi distribuída para fechar esse total.
--
-- Ordem (respeita as FKs):
--   campus, periodo_letivo, professor, sala
--   curso, curriculo, feriado, disciplina
--   curriculo_disciplina, pre_requisito
--   turma, turma_horario
--   aluno
--   matricula, historico, log_matricula

BEGIN;

-- ============================================================
-- CAMPUS
-- ============================================================

-- Dois campi. Os cursos ficam assim: Ciência da Computação no Campus Sul e
-- Engenharia de Computação no Campus Ceilândia.

INSERT INTO campus (nome_campus, cidade_campus) VALUES
    ('Campus Sul (Edson Machado)',        'Brasília'),
    ('Campus Ceilândia (Liliane Barbosa)', 'Brasília');

-- ============================================================
-- PERIODO_LETIVO
-- ============================================================

-- Quatro semestres, um por módulo cursado. 2026/2 é o semestre corrente.
-- Intervalos de data usados pelas consultas de calendário e pelos feriados.

INSERT INTO periodo_letivo
    (ano_periodo_letivo, semestre_periodo_letivo,
     data_inicio_periodo_letivo, data_fim_periodo_letivo) VALUES
    (2025, 1, '2025-02-03', '2025-06-27'),
    (2025, 2, '2025-08-04', '2025-12-12'),
    (2026, 1, '2026-02-02', '2026-06-26'),
    (2026, 2, '2026-08-03', '2026-12-11');

-- ============================================================
-- PROFESSOR
-- ============================================================

-- Nomes fictícios, e-mails em minúsculas (ck_professor_email_minusculo) em
-- domínio iesb.edu.br. titulacao_professor é varchar livre, por definição do
-- modelo.

INSERT INTO professor
    (matricula_professor, nome_professor, email_professor, titulacao_professor) VALUES
    ('PRF0001', 'Helena Prado Siqueira',     'helena.siqueira@iesb.edu.br',   'Doutor'),
    ('PRF0002', 'Marcos Vinícius Teles',     'marcos.teles@iesb.edu.br',      'Mestre'),
    ('PRF0003', 'Beatriz Albuquerque Lima',  'beatriz.lima@iesb.edu.br',      'Doutor'),
    ('PRF0004', 'Rafael Cordeiro Dantas',    'rafael.dantas@iesb.edu.br',     'Mestre'),
    ('PRF0005', 'Luciana Moura Faria',       'luciana.faria@iesb.edu.br',     'Doutor'),
    ('PRF0006', 'Eduardo Nogueira Braga',    'eduardo.braga@iesb.edu.br',     'Especialista'),
    ('PRF0007', 'Camila Rezende Souza',      'camila.souza@iesb.edu.br',      'Mestre'),
    ('PRF0008', 'Tiago Ferraz Medeiros',     'tiago.medeiros@iesb.edu.br',    'Doutor'),
    ('PRF0009', 'Patrícia Valadares Cruz',   'patricia.cruz@iesb.edu.br',     'Mestre'),
    ('PRF0010', 'Gustavo Amaral Pinheiro',   'gustavo.pinheiro@iesb.edu.br',  'Especialista'),
    ('PRF0011', 'Renata Lacerda Vieira',     'renata.vieira@iesb.edu.br',     'Doutor'),
    ('PRF0012', 'Fábio Montenegro Leal',     'fabio.leal@iesb.edu.br',        'Mestre');

-- ============================================================
-- SALA
-- ============================================================

-- Código da sala segue a convenção do IESB: bloco + andar + número.
--   1ª letra = bloco; 2ª letra = andar (A = 1º, B = 2º, C = 3º);
--   número = sala. Ex.: JB3 = bloco J, 2º andar, sala 3.
-- O mesmo código pode existir em campi diferentes (uq_sala_campus_codigo).
-- Laboratórios e auditório ficam em blocos próprios.

INSERT INTO sala (id_campus, codigo_sala, capacidade_sala, tipo_sala)
SELECT c.id_campus, v.codigo, v.capacidade, v.tipo::tipo_sala_t
FROM (VALUES
    -- Campus Sul: bloco J (salas), bloco K (laboratórios), bloco G (auditório)
    ('Campus Sul (Edson Machado)', 'JA1', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JA2', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JA3', 50, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JB1', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JB2', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JB3', 50, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JC1', 40, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JC2', 40, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JC3', 40, 'teorica'),
    ('Campus Sul (Edson Machado)', 'KA1', 30, 'laboratorio'),
    ('Campus Sul (Edson Machado)', 'KA2', 30, 'laboratorio'),
    ('Campus Sul (Edson Machado)', 'KB1', 30, 'laboratorio'),
    ('Campus Sul (Edson Machado)', 'GA1', 150, 'auditorio'),
    -- Campus Ceilândia: bloco D (salas), bloco E (laboratórios), bloco F (auditório)
    ('Campus Ceilândia (Liliane Barbosa)', 'DA1', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DA2', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DA3', 50, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DB1', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DB2', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DB3', 50, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DC1', 40, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DC2', 40, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'EA1', 30, 'laboratorio'),
    ('Campus Ceilândia (Liliane Barbosa)', 'EA2', 30, 'laboratorio'),
    ('Campus Ceilândia (Liliane Barbosa)', 'EB1', 30, 'laboratorio'),
    ('Campus Ceilândia (Liliane Barbosa)', 'FA1', 120, 'auditorio')
) AS v(campus, codigo, capacidade, tipo)
JOIN campus c ON c.nome_campus = v.campus;

COMMIT;
