-- =====================================================================
-- 04_carga.sql
-- Carga de dados: grade real de Ciência da Computação (2023/1) e de
-- Engenharia de Computação, mais alunos, matrículas e histórico gerados
-- com generate_series (mínimo: 100 alunos, 6 turmas, 300 matrículas).
-- Frente: Modelagem Física e Desempenho
-- Banco de Dados II (CCO072) — IESB 2026/2
-- =====================================================================
--
-- Pré-condição: 01, 02 e 03 já rodados, banco vazio.
--
-- Decisões da carga:
--
-- 1. Um módulo por semestre. Os dois cursos têm 8 módulos (1A..4B), um por
--    semestre. Com os 4 períodos carregados, 2026/2 é o módulo 2B:
--        2025/1 -> 1A (periodo 1)    2025/2 -> 1B (periodo 2)
--        2026/1 -> 2A (periodo 3)    2026/2 -> 2B (periodo 4, em andamento)
--    periodo_curriculo_disciplina guarda esse número (1 a 8).
--
-- 2. Tudo é determinístico: sem random(). Rodar a carga duas vezes em bancos
--    limpos gera o mesmo banco, o que permite comparar EXPLAIN antes e
--    depois dos índices.
--
-- 3. Sem ids explícitos: as colunas são GENERATED BY DEFAULT, e inserir um id
--    na mão não avança a sequence. Todas as FKs são resolvidas por chave
--    natural (nome, código, matrícula) via JOIN.
--
-- 4. Dados fictícios: professores e alunos são inventados. Disciplinas,
--    módulos e cargas horárias seguem as grades; onde a grade só informa o
--    total do módulo, a carga foi distribuída para fechar esse total.
--
-- Ordem (respeita as FKs):
--   campus, periodo_letivo, professor, sala
--   curso, curriculo, feriado, disciplina
--   curriculo_disciplina, pre_requisito
--   turma, turma_horario
--   aluno
--   matricula, historico, log_matricula

BEGIN;

-- ============================================================
-- CAMPUS
-- ============================================================

-- Dois campi. Os cursos ficam assim: Ciência da Computação no Campus Sul e
-- Engenharia de Computação no Campus Ceilândia.

INSERT INTO campus (nome_campus, cidade_campus) VALUES
    ('Campus Sul (Edson Machado)',        'Brasília'),
    ('Campus Ceilândia (Liliane Barbosa)', 'Brasília');

-- ============================================================
-- PERIODO_LETIVO
-- ============================================================

-- Quatro semestres, um por módulo cursado. 2026/2 é o semestre corrente.
-- Intervalos de data usados pelas consultas de calendário e pelos feriados.

INSERT INTO periodo_letivo
    (ano_periodo_letivo, semestre_periodo_letivo,
     data_inicio_periodo_letivo, data_fim_periodo_letivo) VALUES
    (2025, 1, '2025-02-03', '2025-06-27'),
    (2025, 2, '2025-08-04', '2025-12-12'),
    (2026, 1, '2026-02-02', '2026-06-26'),
    (2026, 2, '2026-08-03', '2026-12-11');

-- ============================================================
-- PROFESSOR
-- ============================================================

-- Nomes fictícios, e-mails em minúsculas (ck_professor_email_minusculo) em
-- domínio iesb.edu.br. titulacao_professor é varchar livre, por definição do
-- modelo.

INSERT INTO professor
    (matricula_professor, nome_professor, email_professor, titulacao_professor) VALUES
    ('PRF0001', 'Helena Prado Siqueira',     'helena.siqueira@iesb.edu.br',   'Doutor'),
    ('PRF0002', 'Marcos Vinícius Teles',     'marcos.teles@iesb.edu.br',      'Mestre'),
    ('PRF0003', 'Beatriz Albuquerque Lima',  'beatriz.lima@iesb.edu.br',      'Doutor'),
    ('PRF0004', 'Rafael Cordeiro Dantas',    'rafael.dantas@iesb.edu.br',     'Mestre'),
    ('PRF0005', 'Luciana Moura Faria',       'luciana.faria@iesb.edu.br',     'Doutor'),
    ('PRF0006', 'Eduardo Nogueira Braga',    'eduardo.braga@iesb.edu.br',     'Especialista'),
    ('PRF0007', 'Camila Rezende Souza',      'camila.souza@iesb.edu.br',      'Mestre'),
    ('PRF0008', 'Tiago Ferraz Medeiros',     'tiago.medeiros@iesb.edu.br',    'Doutor'),
    ('PRF0009', 'Patrícia Valadares Cruz',   'patricia.cruz@iesb.edu.br',     'Mestre'),
    ('PRF0010', 'Gustavo Amaral Pinheiro',   'gustavo.pinheiro@iesb.edu.br',  'Especialista'),
    ('PRF0011', 'Renata Lacerda Vieira',     'renata.vieira@iesb.edu.br',     'Doutor'),
    ('PRF0012', 'Fábio Montenegro Leal',     'fabio.leal@iesb.edu.br',        'Mestre');

-- ============================================================
-- SALA
-- ============================================================

-- Código da sala segue a convenção do IESB: bloco + andar + número.
--   1ª letra = bloco; 2ª letra = andar (A = 1º, B = 2º, C = 3º);
--   número = sala. Ex.: JB3 = bloco J, 2º andar, sala 3.
-- O mesmo código pode existir em campi diferentes (uq_sala_campus_codigo).
-- Laboratórios e auditório ficam em blocos próprios.

INSERT INTO sala (id_campus, codigo_sala, capacidade_sala, tipo_sala)
SELECT c.id_campus, v.codigo, v.capacidade, v.tipo::tipo_sala_t
FROM (VALUES
    -- Campus Sul: bloco J (salas), bloco K (laboratórios), bloco G (auditório)
    ('Campus Sul (Edson Machado)', 'JA1', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JA2', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JA3', 50, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JB1', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JB2', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JB3', 50, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JC1', 40, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JC2', 40, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JC3', 40, 'teorica'),
    ('Campus Sul (Edson Machado)', 'KA1', 30, 'laboratorio'),
    ('Campus Sul (Edson Machado)', 'KA2', 30, 'laboratorio'),
    ('Campus Sul (Edson Machado)', 'KB1', 30, 'laboratorio'),
    ('Campus Sul (Edson Machado)', 'GA1', 150, 'auditorio'),
    -- Campus Ceilândia: bloco D (salas), bloco E (laboratórios), bloco F (auditório)
    ('Campus Ceilândia (Liliane Barbosa)', 'DA1', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DA2', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DA3', 50, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DB1', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DB2', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DB3', 50, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DC1', 40, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DC2', 40, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'EA1', 30, 'laboratorio'),
    ('Campus Ceilândia (Liliane Barbosa)', 'EA2', 30, 'laboratorio'),
    ('Campus Ceilândia (Liliane Barbosa)', 'EB1', 30, 'laboratorio'),
    ('Campus Ceilândia (Liliane Barbosa)', 'FA1', 120, 'auditorio')
) AS v(campus, codigo, capacidade, tipo)
JOIN campus c ON c.nome_campus = v.campus;

-- ============================================================
-- CURSO
-- ============================================================

-- ch_total_curso é o total oficial do curso, denormalizado (não dá para ser
-- coluna gerada: depende de outras linhas).
--   CCO: 3.280 h de grade + 120 h de atividades complementares = 3.400 h
--        (valor da própria grade de 2023/1).
--   ECO: soma das cargas horárias da matriz curricular (3.790 h). A matriz
--        não informa o total; este é o somatório das disciplinas.

INSERT INTO curso (codigo_curso, nome_curso, grau_curso, ch_total_curso, id_campus)
SELECT v.codigo, v.nome, v.grau, v.ch_total, c.id_campus
FROM (VALUES
    ('CCO', 'Ciência da Computação',     'Bacharelado', 3400, 'Campus Sul (Edson Machado)'),
    ('ECO', 'Engenharia de Computação',  'Bacharelado', 3790, 'Campus Ceilândia (Liliane Barbosa)')
) AS v(codigo, nome, grau, ch_total, campus)
JOIN campus c ON c.nome_campus = v.campus;

-- ============================================================
-- CURRICULO
-- ============================================================

-- Uma grade vigente por curso. CCO segue a grade 2023/1; a matriz de ECO não
-- traz ano, então usa-se 2023 também. Novos currículos nascem ativos
-- (DEFAULT true).

INSERT INTO curriculo (id_curso, ano_vigencia_curriculo)
SELECT id_curso, 2023
FROM curso
WHERE codigo_curso IN ('CCO', 'ECO');

-- ============================================================
-- FERIADO
-- ============================================================

-- id_campus NULL = feriado nacional (vale para todos os campi).
-- Dia do Evangélico é feriado do DF: aparece uma vez por campus. A mesma data
-- em campi diferentes é permitida; a duplicata de um nacional não seria
-- (UNIQUE NULLS NOT DISTINCT em uq_feriado_data_campus).

INSERT INTO feriado (data_feriado, descricao_feriado, id_campus) VALUES
    ('2025-04-18', 'Sexta-feira Santa',           NULL),
    ('2025-04-21', 'Tiradentes',                  NULL),
    ('2025-05-01', 'Dia do Trabalho',             NULL),
    ('2025-06-19', 'Corpus Christi',              NULL),
    ('2025-09-07', 'Independência do Brasil',     NULL),
    ('2025-10-12', 'Nossa Senhora Aparecida',     NULL),
    ('2025-11-02', 'Finados',                     NULL),
    ('2025-11-15', 'Proclamação da República',    NULL),
    ('2025-11-20', 'Dia da Consciência Negra',    NULL),
    ('2025-12-25', 'Natal',                       NULL),
    ('2026-04-03', 'Sexta-feira Santa',           NULL),
    ('2026-04-21', 'Tiradentes',                  NULL),
    ('2026-05-01', 'Dia do Trabalho',             NULL),
    ('2026-06-04', 'Corpus Christi',              NULL),
    ('2026-09-07', 'Independência do Brasil',     NULL),
    ('2026-10-12', 'Nossa Senhora Aparecida',     NULL),
    ('2026-11-02', 'Finados',                     NULL),
    ('2026-11-15', 'Proclamação da República',    NULL),
    ('2026-11-20', 'Dia da Consciência Negra',    NULL),
    ('2026-12-25', 'Natal',                       NULL);

INSERT INTO feriado (data_feriado, descricao_feriado, id_campus)
SELECT d.data_feriado, 'Dia do Evangélico (DF)', c.id_campus
FROM (VALUES ('2025-11-30'::date), ('2026-11-30'::date)) AS d(data_feriado)
CROSS JOIN campus c;

-- ============================================================
-- DISCIPLINA
-- ============================================================

-- Catálogo único para os dois cursos: disciplina independe de curso e
-- currículo (o vínculo vive em curriculo_disciplina). Disciplinas que as duas
-- grades têm em comum, com a mesma carga horária, são uma linha só.
-- Exemplo: Cálculo II e Estrutura de Dados.
--   - "Banco de Dados" de ECO é a mesma disciplina que "Banco de Dados I" de CCO.
--   - "Redes de Computadores" de ECO é "Redes de Computadores I" de CCO.
--   - Atividades de Extensão, Projetos Integradores, Estágios e TCC/Projeto de
--     Graduação são disciplinas distintas, uma por etapa. A matriz de ECO repete
--     o nome "Projeto de Extensão na Educação Superior" em três semestres; aqui
--     ganham sufixo I, II e III para o catálogo não ter nomes duplicados.
--   - "Eletiva" (CCO) e "Optativa" (ECO) são vagas na grade, não matérias.
--
-- ch_teorica_disciplina + ch_pratica_disciplina dão a carga total (coluna
-- gerada). Onde a grade só informa o total do módulo, a carga foi distribuída
-- para fechar esse total. A divisão teórica/prática é uma estimativa:
-- laboratórios, extensão, projetos e estágios são 100% práticos.
-- ementa_disciplina fica NULL: pode ser cadastrada depois.
--
-- Código: mnemônico de até 10 caracteres.

INSERT INTO disciplina
    (codigo_disciplina, nome_disciplina, ch_teorica_disciplina, ch_pratica_disciplina)
VALUES
    -- Comuns a CCO e ECO (25)
    ('ALP1', 'Algoritmos e Programação de Computadores I',  40, 20),
    ('ALP2', 'Algoritmos e Programação de Computadores II', 40, 20),
    ('CAL1', 'Cálculo I',                                   90,  0),
    ('CAL2', 'Cálculo II',                                  60,  0),
    ('SDG',  'Sistemas Digitais',                           40, 20),
    ('BD1',  'Banco de Dados I',                            40, 20),
    ('AOC',  'Arquitetura e Organização de Computadores',   40, 20),
    ('ED',   'Estrutura de Dados',                          40, 20),
    ('POO',  'Programação Orientada a Objetos',             40, 20),
    ('PES',  'Probabilidade e Estatística',                 60,  0),
    ('CNU',  'Cálculo Numérico',                            60,  0),
    ('ANA',  'Análise de Algoritmos',                       60,  0),
    ('ESW',  'Engenharia de Software',                      40, 20),
    ('SO',   'Sistemas Operacionais',                       40, 20),
    ('IA1',  'Inteligência Artificial',                     40, 20),
    ('CGR',  'Computação Gráfica',                          40, 20),
    ('PLP',  'Paradigmas de Linguagens de Programação',     60,  0),
    ('PDM',  'Programação para Dispositivos Móveis',        30, 30),
    ('TWB',  'Tecnologias Web',                             30, 30),
    ('RC1',  'Redes de Computadores I',                     40, 20),
    ('TGR',  'Teoria dos Grafos',                           60,  0),
    ('LFA',  'Linguagens Formais e Autômatos',              60,  0),
    ('SDI',  'Sistemas Distribuídos',                       40, 20),
    ('CMP',  'Compiladores',                                40, 20),
    ('TCO',  'Tópicos em Computação',                       60,  0),

    -- Só Ciência da Computação (31)
    ('TMA',  'Tópicos de Matemática',                       60,  0),
    ('AEX1', 'Atividade de Extensão I',                      0, 30),
    ('AEX2', 'Atividade de Extensão II',                     0, 30),
    ('AEX3', 'Atividade de Extensão III',                    0, 30),
    ('AEX4', 'Atividade de Extensão IV',                     0, 30),
    ('AEX5', 'Atividade de Extensão V',                      0, 30),
    ('FLG',  'Fundamentos de Lógica',                       60,  0),
    ('GAV',  'Geometria Analítica e Vetores',               60,  0),
    ('MDI',  'Matemática Discreta',                         60,  0),
    ('LP1',  'Laboratório de Práticas I',                    0, 60),
    ('LP2',  'Laboratório de Práticas II',                   0, 30),
    ('CSP',  'Cultura, Sociedade e Política',               60,  0),
    ('ALG',  'Álgebra Linear',                              60,  0),
    ('DHA',  'Direitos Humanos e Ambientais',               60,  0),
    ('TCP',  'Teoria da Computação',                        60,  0),
    ('PI2A', 'Projeto Integrador 2A',                        0, 90),
    ('BD2',  'Banco de Dados II',                           40, 20),
    ('GTI',  'Governança de TI e Mapeamento de Processos',  60,  0),
    ('PI3A', 'Projeto Integrador 3A',                        0, 30),
    ('PPA',  'Programação Paralela',                        40, 20),
    ('PI3B', 'Projeto Integrador 3B',                        0, 90),
    ('ELV',  'Eletiva',                                     60,  0),
    ('IA2',  'Inteligência Artificial II',                  40, 20),
    ('TBD',  'Tópicos em Banco de Dados',                   40, 20),
    ('EST1', 'Estágio Supervisionado I',                     0, 80),
    ('PGA',  'Projeto de Graduação CCO A',                  20, 60),
    ('PIM',  'Processamento de Imagens',                    40, 20),
    ('SCM',  'Sistemas de Comunicação',                     60,  0),
    ('STR',  'Sistemas de Tempo Real',                      40, 20),
    ('EST2', 'Estágio Supervisionado II',                    0, 80),
    ('PGB',  'Projeto de Graduação CCO B',                  20, 60),

    -- Só Engenharia de Computação (36)
    ('PEN',  'Práticas de Engenharia',                      30, 30),
    ('LCA',  'Laboratório de Circuitos Analógicos',          0, 30),
    ('QMA',  'Química e Materiais',                         40, 20),
    ('EMC',  'Estruturas Matemáticas para Computação',      60,  0),
    ('FCC',  'Fundamentos de Cálculo para Computação e Engenharia', 60, 0),
    ('SCD',  'Sociedade, Cultura, Direitos Humanos e Ambientais',   60, 0),
    ('ALA',  'Álgebra Linear e Aplicações',                 60,  0),
    ('LSD',  'Laboratório de Sistemas Digitais',             0, 30),
    ('EGR',  'Expressão Gráfica',                           10, 20),
    ('EDG',  'Eletrônica Digital',                          40, 20),
    ('PIED', 'Projeto Integrador - Eletrônica Digital',      0, 30),
    ('PEE1', 'Projeto de Extensão na Educação Superior I',   0, 130),
    ('FEC',  'Física para Engenharia da Computação',        60,  0),
    ('CEL',  'Circuitos Elétricos',                         40, 20),
    ('MME',  'Métodos Matemáticos em Engenharia',           60,  0),
    ('PEE2', 'Projeto de Extensão na Educação Superior II',  0, 130),
    ('CAL3', 'Cálculo III',                                 60,  0),
    ('ASI',  'Análise de Sinais',                           60,  0),
    ('EBA',  'Eletrônica Básica',                           40, 20),
    ('CEL2', 'Circuitos Elétricos II',                      40, 20),
    ('MSF',  'Mecânica dos Sólidos e Fenômenos de Transporte', 60, 0),
    ('SLI',  'Sistemas Lineares',                           60,  0),
    ('SEM',  'Sistemas Embarcados',                         40, 20),
    ('PISE', 'Projeto Integrador - Sistemas Embarcados',     0, 30),
    ('PEE3', 'Projeto de Extensão na Educação Superior III', 0, 130),
    ('ADE',  'Administração e Economia',                    60,  0),
    ('PDS',  'Processamento Digital de Sinais',             40, 20),
    ('MCS',  'Modelagem e Controle de Sistemas',            60,  0),
    ('TCC1', 'Trabalho de Conclusão de Curso I - Eng Comp', 20, 40),
    ('PSM',  'Processamento de Sinais Multimídia',          40, 20),
    ('ESA',  'Estágio Supervisionado - Aplicação Profissional',  0, 80),
    ('OPT',  'Optativa',                                    60,  0),
    ('TIC',  'Teoria da Informação e Codificação',          60,  0),
    ('TCC2', 'Trabalho de Conclusão de Curso II - Eng Comp', 20, 40),
    ('ESI',  'Estágio Supervisionado - Integração Profissional', 0, 80),
    ('MDD',  'Mineração de Dados',                          40, 20);

-- ============================================================
-- CURRICULO_DISCIPLINA
-- ============================================================

-- Composição de cada grade: em que semestre da GRADE (1, 2, 3...) cada
-- disciplina aparece. Não confundir com periodo_letivo, que é o semestre de
-- calendário. Cada linha do VALUES é um módulo da grade:
--   CCO: 1A=1, 1B=2, 2A=3, 2B=4, 3A=5, 3B=6, 4A=7, 4B=8
--   ECO: mesma regra, até 5B=10.
--
-- Tudo é 'obrigatoria', exceto as vagas de escolha: 'Eletiva' (CCO) é
-- 'eletiva' e 'Optativa' (ECO) é 'optativa'.
--
-- Um código com erro de digitação não some em silêncio: o subselect devolve
-- NULL e a coluna id_disciplina (NOT NULL) rejeita a linha.

INSERT INTO curriculo_disciplina
    (id_curriculo, id_disciplina, periodo_curriculo_disciplina, tipo_curriculo_disciplina)
SELECT
    (SELECT k.id_curriculo
       FROM curriculo k JOIN curso c ON c.id_curso = k.id_curso
      WHERE c.codigo_curso = m.curso),
    (SELECT d.id_disciplina FROM disciplina d WHERE d.codigo_disciplina = u.codigo),
    m.periodo,
    (CASE u.codigo
         WHEN 'ELV' THEN 'eletiva'
         WHEN 'OPT' THEN 'optativa'
         ELSE 'obrigatoria'
     END)::tipo_disc_t
FROM (VALUES
    -- Ciência da Computação (grade 2023/1) — 56 disciplinas
    ('CCO', 1, ARRAY['TMA','ALP1','AEX1','FLG','GAV','MDI','LP1','CSP']),
    ('CCO', 2, ARRAY['CAL1','ALP2','ALG','AEX2','BD1','DHA','SDG','LP2']),
    ('CCO', 3, ARRAY['CAL2','AOC','AEX3','ED','PI2A','TCP']),
    ('CCO', 4, ARRAY['BD2','ESW','IA1','POO','SO','GTI']),
    ('CCO', 5, ARRAY['AEX4','CNU','CGR','PLP','PDM','PI3A','TWB','PES']),
    ('CCO', 6, ARRAY['AEX5','LFA','PPA','PI3B','RC1','TGR']),
    ('CCO', 7, ARRAY['ANA','ELV','IA2','SDI','TBD','EST1','PGA']),
    ('CCO', 8, ARRAY['CMP','PIM','SCM','STR','TCO','EST2','PGB']),
    -- Engenharia de Computação — 61 disciplinas
    ('ECO', 1,  ARRAY['PEN','LCA','QMA','ALP1','EMC','FCC','SCD']),
    ('ECO', 2,  ARRAY['SDG','CAL1','ALP2','ALA','BD1','LSD','EGR']),
    ('ECO', 3,  ARRAY['EDG','PIED','PEE1','AOC','CAL2','ED','FEC']),
    ('ECO', 4,  ARRAY['CEL','MME','PEE2','CAL3','PES','POO']),
    ('ECO', 5,  ARRAY['ASI','EBA','CEL2','CNU','MSF','ANA']),
    ('ECO', 6,  ARRAY['SLI','SEM','PISE','PEE3','IA1','CGR','ADE']),
    ('ECO', 7,  ARRAY['PDS','MCS','ESW','PDM','PLP']),
    ('ECO', 8,  ARRAY['TWB','RC1','TGR','LFA','SO']),
    ('ECO', 9,  ARRAY['TCC1','PSM','ESA','OPT','SDI']),
    ('ECO', 10, ARRAY['TIC','TCC2','ESI','TCO','CMP','MDD'])
) AS m(curso, periodo, codigos)
CROSS JOIN LATERAL unnest(m.codigos) AS u(codigo);

-- ============================================================
-- PRE_REQUISITO
-- ============================================================

-- Fonte: "Tabela de Pré-Requisitos" de CCO e de Engenharia de Computação.
-- Leitura de cada linha: (disciplina, requisito, vínculo) = a disciplina exige
-- o requisito. Regras de transcrição:
--   - "deve ser cursado junto com" e "(matr)"  -> co_requisito
--   - os demais                                -> pre_requisito
--   - um requisito que aparece nas duas tabelas entra uma vez só
--
-- Fica de fora o que não é "disciplina exige disciplina":
--   - "75% CH concluída" (Tópicos em Computação) e a regra de 75% das
--     disciplinas teóricas para TCC e Projeto de Graduação. É uma regra sobre o
--     histórico do aluno, não uma relação entre duas disciplinas. Fica para a
--     aplicação/consulta.
--   - AMM, Automação e Robótica, Princípios de Controle e Projeto Integrador 3A
--     de Engenharia: a tabela os cita, mas não estão na matriz curricular de
--     Engenharia usada no catálogo.
--
-- pre_requisito é do catálogo, não de um currículo (a tabela não tem curso).
-- Duas disciplinas têm exigência diferente em cada curso, e as duas linhas
-- entram:
--   Sistemas Digitais:      CCO exige Fund. de Lógica; ECO exige Práticas de Eng.
--   Linguagens Formais:     CCO exige Teoria da Computação; ECO exige Estr. de Dados.
-- Para um aluno, só valem os requisitos que existem na grade do curso dele.
-- A conferência no fim do bloco trata exatamente isso.
--
-- As cadeias mais longas, só de pre_requisito, têm 4 níveis, ex.:
-- Compiladores -> Linguagens Formais -> Estrutura de Dados -> Algoritmos II ->
-- Algoritmos I.

INSERT INTO pre_requisito
    (id_disciplina, id_disciplina_requisito, vinculo_pre_requisito)
SELECT
    (SELECT id_disciplina FROM disciplina WHERE codigo_disciplina = v.disciplina),
    (SELECT id_disciplina FROM disciplina WHERE codigo_disciplina = v.requisito),
    v.vinculo::vinculo_t
FROM (VALUES
    -- Tabela de CCO
    ('ALG',  'GAV',  'pre_requisito'),
    ('ANA',  'ED',   'pre_requisito'),
    ('ALP2', 'ALP1', 'pre_requisito'),
    ('AOC',  'SDG',  'pre_requisito'),
    ('BD1',  'MDI',  'pre_requisito'),
    ('BD2',  'BD1',  'pre_requisito'),
    ('CNU',  'CAL2', 'pre_requisito'),
    ('CAL1', 'TMA',  'pre_requisito'),
    ('CAL2', 'CAL1', 'pre_requisito'),
    ('CMP',  'LFA',  'pre_requisito'),
    ('CGR',  'CAL1', 'pre_requisito'),
    ('CGR',  'ALG',  'pre_requisito'),
    ('ESW',  'BD1',  'pre_requisito'),
    ('ED',   'ALP2', 'pre_requisito'),
    ('IA1',  'ALP2', 'pre_requisito'),
    ('IA2',  'IA1',  'pre_requisito'),
    ('LFA',  'TCP',  'pre_requisito'),
    ('PDM',  'POO',  'pre_requisito'),
    ('PDM',  'ED',   'pre_requisito'),
    ('PLP',  'ED',   'pre_requisito'),
    ('POO',  'ALP2', 'pre_requisito'),
    ('PES',  'CAL1', 'pre_requisito'),
    ('PIM',  'CAL2', 'pre_requisito'),
    ('PPA',  'ED',   'pre_requisito'),
    ('PI2A', 'ED',   'co_requisito'),
    ('PI3A', 'PDM',  'co_requisito'),
    ('PI3B', 'TGR',  'co_requisito'),
    ('RC1',  'PES',  'pre_requisito'),
    ('SCM',  'PES',  'pre_requisito'),
    ('SCM',  'ALG',  'pre_requisito'),
    ('SDG',  'FLG',  'pre_requisito'),
    ('SDI',  'SO',   'pre_requisito'),
    ('STR',  'ED',   'pre_requisito'),
    ('SO',   'ALP2', 'pre_requisito'),
    ('TCP',  'FLG',  'pre_requisito'),
    ('TGR',  'ED',   'pre_requisito'),
    ('TBD',  'BD2',  'pre_requisito'),
    -- Tabela de Engenharia de Computação (só o que não repete a de CCO)
    ('ASI',  'MME',  'pre_requisito'),
    ('CAL3', 'CAL2', 'pre_requisito'),
    ('CEL',  'PEN',  'pre_requisito'),
    ('CEL2', 'CEL',  'pre_requisito'),
    ('CEL2', 'MME',  'pre_requisito'),
    ('EDG',  'SDG',  'pre_requisito'),
    ('EBA',  'CEL',  'pre_requisito'),
    ('LFA',  'ED',   'pre_requisito'),
    ('MME',  'CAL2', 'co_requisito'),
    ('PDS',  'SLI',  'pre_requisito'),
    ('PIED', 'EDG',  'co_requisito'),
    ('PSM',  'PDS',  'pre_requisito'),
    ('SDG',  'PEN',  'pre_requisito'),
    ('SLI',  'ASI',  'pre_requisito'),
    ('TIC',  'SLI',  'pre_requisito')
) AS v(disciplina, requisito, vinculo);

-- Conferência: a coerência entre pre_requisito e as grades envolve três
-- tabelas e não cabe em constraint. Se a carga violar alguma regra, o script
-- para aqui em vez de seguir com dados incoerentes.
--
-- Como pre_requisito é do catálogo, a regra vale por currículo e só olha os
-- pares em que disciplina e requisito estão na mesma grade:
--   1. pre_requisito: o requisito vem em semestre anterior da grade;
--   2. co_requisito: o requisito vem no mesmo semestre ou antes;
--   3. toda linha vale em pelo menos uma grade (senão seria letra morta).

DO $$
DECLARE
    violacoes integer;
BEGIN
    SELECT count(*) INTO violacoes
    FROM pre_requisito p
    JOIN curriculo_disciplina cd ON cd.id_disciplina = p.id_disciplina
    JOIN curriculo_disciplina rq
      ON rq.id_curriculo = cd.id_curriculo
     AND rq.id_disciplina = p.id_disciplina_requisito
    WHERE p.vinculo_pre_requisito = 'pre_requisito'
      AND rq.periodo_curriculo_disciplina >= cd.periodo_curriculo_disciplina;
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % pre_requisito(s) com requisito em semestre igual ou posterior', violacoes;
    END IF;

    SELECT count(*) INTO violacoes
    FROM pre_requisito p
    JOIN curriculo_disciplina cd ON cd.id_disciplina = p.id_disciplina
    JOIN curriculo_disciplina rq
      ON rq.id_curriculo = cd.id_curriculo
     AND rq.id_disciplina = p.id_disciplina_requisito
    WHERE p.vinculo_pre_requisito = 'co_requisito'
      AND rq.periodo_curriculo_disciplina > cd.periodo_curriculo_disciplina;
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % co_requisito(s) com requisito em semestre posterior', violacoes;
    END IF;

    SELECT count(*) INTO violacoes
    FROM pre_requisito p
    WHERE NOT EXISTS (
        SELECT 1
        FROM curriculo_disciplina cd
        JOIN curriculo_disciplina rq ON rq.id_curriculo = cd.id_curriculo
        WHERE cd.id_disciplina = p.id_disciplina
          AND rq.id_disciplina = p.id_disciplina_requisito
    );
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % pre_requisito(s) que não valem em nenhuma grade', violacoes;
    END IF;
END
$$;

COMMIT;
