-- =====================================================================
-- 04_carga.sql
-- Carga de dados: grade real de Ciência da Computação (2023/1) e de
-- Engenharia de Computação, mais alunos, matrículas e histórico gerados
-- com generate_series (mínimo: 100 alunos, 6 turmas, 300 matrículas).
-- Frente: Modelagem Física e Desempenho
-- Banco de Dados II (CCO072) — IESB 2026/2
-- =====================================================================
--
-- Pré-condição: 01_ddl.sql já rodado, banco vazio.
--
-- Decisões da carga:
--
-- 1. Um módulo por semestre. Os dois cursos têm 8 módulos (1A..4B), um por
--    semestre. Com os 4 períodos carregados, 2026/2 é o módulo 2B:
--        2025/1 -> 1A (periodo 1)    2025/2 -> 1B (periodo 2)
--        2026/1 -> 2A (periodo 3)    2026/2 -> 2B (periodo 4, em andamento)
--    periodo_curriculo_disciplina guarda esse número (1 a 8).
--
-- 2. Tudo é determinístico: sem random(). Rodar a carga duas vezes em bancos
--    limpos gera o mesmo banco, o que permite comparar EXPLAIN antes e
--    depois dos índices.
--
-- 3. Sem ids explícitos: as colunas são GENERATED BY DEFAULT, e inserir um id
--    na mão não avança a sequence. Todas as FKs são resolvidas por chave
--    natural (nome, código, matrícula) via JOIN.
--
-- 4. Dados fictícios: professores e alunos são inventados. Disciplinas,
--    módulos e cargas horárias seguem as grades; onde a grade só informa o
--    total do módulo, a carga foi distribuída para fechar esse total.
--
-- Ordem (respeita as FKs):
--   tb_campus, tb_periodo_letivo, tb_professor, tb_sala
--   tb_curso, tb_curriculo, tb_feriado, tb_disciplina
--   tb_curriculo_disciplina, tb_pre_requisito
--   tb_turma, tb_turma_horario
--   tb_aluno
--   tb_matricula, tb_historico, tb_log_matricula

BEGIN;

-- ============================================================
-- CAMPUS
-- ============================================================

-- Dois campi. Os cursos ficam assim: Ciência da Computação no Campus Sul e
-- Engenharia de Computação no Campus Ceilândia.

INSERT INTO tb_campus (nome_campus, cidade_campus) VALUES
    ('Campus Sul (Edson Machado)',        'Brasília'),
    ('Campus Ceilândia (Liliane Barbosa)', 'Brasília');

-- ============================================================
-- PERIODO_LETIVO
-- ============================================================

-- Quatro semestres, um por módulo cursado. 2026/2 é o semestre corrente.
-- Intervalos de data usados pelas consultas de calendário e pelos feriados.

INSERT INTO tb_periodo_letivo
    (ano_periodo_letivo, semestre_periodo_letivo,
     data_inicio_periodo_letivo, data_fim_periodo_letivo) VALUES
    (2025, 1, '2025-02-03', '2025-06-27'),
    (2025, 2, '2025-08-04', '2025-12-12'),
    (2026, 1, '2026-02-02', '2026-06-26'),
    (2026, 2, '2026-08-03', '2026-12-11');

-- ============================================================
-- PROFESSOR
-- ============================================================

-- Nomes fictícios, e-mails em minúsculas (ck_professor_email_minusculo) em
-- domínio iesb.edu.br. titulacao_professor é varchar livre, por definição do
-- modelo.

INSERT INTO tb_professor
    (matricula_professor, nome_professor, email_professor, titulacao_professor) VALUES
    ('PRF0001', 'Helena Prado Siqueira',     'helena.siqueira@iesb.edu.br',   'Doutor'),
    ('PRF0002', 'Marcos Vinícius Teles',     'marcos.teles@iesb.edu.br',      'Mestre'),
    ('PRF0003', 'Beatriz Albuquerque Lima',  'beatriz.lima@iesb.edu.br',      'Doutor'),
    ('PRF0004', 'Rafael Cordeiro Dantas',    'rafael.dantas@iesb.edu.br',     'Mestre'),
    ('PRF0005', 'Luciana Moura Faria',       'luciana.faria@iesb.edu.br',     'Doutor'),
    ('PRF0006', 'Eduardo Nogueira Braga',    'eduardo.braga@iesb.edu.br',     'Especialista'),
    ('PRF0007', 'Camila Rezende Souza',      'camila.souza@iesb.edu.br',      'Mestre'),
    ('PRF0008', 'Tiago Ferraz Medeiros',     'tiago.medeiros@iesb.edu.br',    'Doutor'),
    ('PRF0009', 'Patrícia Valadares Cruz',   'patricia.cruz@iesb.edu.br',     'Mestre'),
    ('PRF0010', 'Gustavo Amaral Pinheiro',   'gustavo.pinheiro@iesb.edu.br',  'Especialista'),
    ('PRF0011', 'Renata Lacerda Vieira',     'renata.vieira@iesb.edu.br',     'Doutor'),
    ('PRF0012', 'Fábio Montenegro Leal',     'fabio.leal@iesb.edu.br',        'Mestre');

-- ============================================================
-- SALA
-- ============================================================

-- Código da sala segue a convenção do IESB: bloco + andar + número.
--   1ª letra = bloco; 2ª letra = andar (A = 1º, B = 2º, C = 3º);
--   número = sala. Ex.: JB3 = bloco J, 2º andar, sala 3.
-- O mesmo código pode existir em campi diferentes (uq_sala_campus_codigo).
-- Laboratórios e auditório ficam em blocos próprios.

INSERT INTO tb_sala (id_campus, codigo_sala, capacidade_sala, tipo_sala)
SELECT c.id_campus, v.codigo, v.capacidade, v.tipo::tipo_sala_t
FROM (VALUES
    -- Campus Sul: bloco J (salas), bloco K (laboratórios), bloco G (auditório)
    ('Campus Sul (Edson Machado)', 'JA1', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JA2', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JA3', 50, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JB1', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JB2', 45, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JB3', 50, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JC1', 40, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JC2', 40, 'teorica'),
    ('Campus Sul (Edson Machado)', 'JC3', 40, 'teorica'),
    ('Campus Sul (Edson Machado)', 'KA1', 45, 'laboratorio'),
    ('Campus Sul (Edson Machado)', 'KA2', 45, 'laboratorio'),
    ('Campus Sul (Edson Machado)', 'KB1', 45, 'laboratorio'),
    ('Campus Sul (Edson Machado)', 'GA1', 150, 'auditorio'),
    -- Campus Ceilândia: bloco D (salas), bloco E (laboratórios), bloco F (auditório)
    ('Campus Ceilândia (Liliane Barbosa)', 'DA1', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DA2', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DA3', 50, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DB1', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DB2', 45, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DB3', 50, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DC1', 40, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'DC2', 40, 'teorica'),
    ('Campus Ceilândia (Liliane Barbosa)', 'EA1', 45, 'laboratorio'),
    ('Campus Ceilândia (Liliane Barbosa)', 'EA2', 45, 'laboratorio'),
    ('Campus Ceilândia (Liliane Barbosa)', 'EB1', 45, 'laboratorio'),
    ('Campus Ceilândia (Liliane Barbosa)', 'FA1', 120, 'auditorio')
) AS v(campus, codigo, capacidade, tipo)
JOIN tb_campus c ON c.nome_campus = v.campus;

-- ============================================================
-- CURSO
-- ============================================================

-- ch_total_curso é o total oficial do curso, denormalizado (não dá para ser
-- coluna gerada: depende de outras linhas).
--   CCO: 3.280 h de grade + 120 h de atividades complementares = 3.400 h
--        (valor da própria grade de 2023/1).
--   ECO: soma das cargas horárias da matriz curricular (3.790 h). A matriz
--        não informa o total; este é o somatório das disciplinas.

INSERT INTO tb_curso (codigo_curso, nome_curso, grau_curso, ch_total_curso, id_campus)
SELECT v.codigo, v.nome, v.grau, v.ch_total, c.id_campus
FROM (VALUES
    ('CCO', 'Ciência da Computação',     'Bacharelado', 3400, 'Campus Sul (Edson Machado)'),
    ('ECO', 'Engenharia de Computação',  'Bacharelado', 3790, 'Campus Ceilândia (Liliane Barbosa)')
) AS v(codigo, nome, grau, ch_total, campus)
JOIN tb_campus c ON c.nome_campus = v.campus;

-- ============================================================
-- CURRICULO
-- ============================================================

-- Uma grade vigente por curso. CCO segue a grade 2023/1; a matriz de ECO não
-- traz ano, então usa-se 2023 também. Novos currículos nascem ativos
-- (DEFAULT true).

INSERT INTO tb_curriculo (id_curso, ano_vigencia_curriculo)
SELECT id_curso, 2023
FROM tb_curso
WHERE codigo_curso IN ('CCO', 'ECO');

-- ============================================================
-- FERIADO
-- ============================================================

-- id_campus NULL = feriado nacional (vale para todos os campi).
-- Dia do Evangélico é feriado do DF: aparece uma vez por campus. A mesma data
-- em campi diferentes é permitida; a duplicata de um nacional não seria
-- (UNIQUE NULLS NOT DISTINCT em uq_feriado_data_campus).

INSERT INTO tb_feriado (data_feriado, descricao_feriado, id_campus) VALUES
    ('2025-04-18', 'Sexta-feira Santa',           NULL),
    ('2025-04-21', 'Tiradentes',                  NULL),
    ('2025-05-01', 'Dia do Trabalho',             NULL),
    ('2025-06-19', 'Corpus Christi',              NULL),
    ('2025-09-07', 'Independência do Brasil',     NULL),
    ('2025-10-12', 'Nossa Senhora Aparecida',     NULL),
    ('2025-11-02', 'Finados',                     NULL),
    ('2025-11-15', 'Proclamação da República',    NULL),
    ('2025-11-20', 'Dia da Consciência Negra',    NULL),
    ('2025-12-25', 'Natal',                       NULL),
    ('2026-04-03', 'Sexta-feira Santa',           NULL),
    ('2026-04-21', 'Tiradentes',                  NULL),
    ('2026-05-01', 'Dia do Trabalho',             NULL),
    ('2026-06-04', 'Corpus Christi',              NULL),
    ('2026-09-07', 'Independência do Brasil',     NULL),
    ('2026-10-12', 'Nossa Senhora Aparecida',     NULL),
    ('2026-11-02', 'Finados',                     NULL),
    ('2026-11-15', 'Proclamação da República',    NULL),
    ('2026-11-20', 'Dia da Consciência Negra',    NULL),
    ('2026-12-25', 'Natal',                       NULL);

INSERT INTO tb_feriado (data_feriado, descricao_feriado, id_campus)
SELECT d.data_feriado, 'Dia do Evangélico (DF)', c.id_campus
FROM (VALUES ('2025-11-30'::date), ('2026-11-30'::date)) AS d(data_feriado)
CROSS JOIN tb_campus c;

-- ============================================================
-- DISCIPLINA
-- ============================================================

-- Catálogo único para os dois cursos: disciplina independe de curso e
-- currículo (o vínculo vive em curriculo_disciplina). Disciplinas que as duas
-- grades têm em comum, com a mesma carga horária, são uma linha só.
-- Exemplo: Cálculo II e Estrutura de Dados.
--   - "Banco de Dados" de ECO é a mesma disciplina que "Banco de Dados I" de CCO.
--   - "Redes de Computadores" de ECO é "Redes de Computadores I" de CCO.
--   - Atividades de Extensão, Projetos Integradores, Estágios e TCC/Projeto de
--     Graduação são disciplinas distintas, uma por etapa. A matriz de ECO repete
--     o nome "Projeto de Extensão na Educação Superior" em três semestres; aqui
--     ganham sufixo I, II e III para o catálogo não ter nomes duplicados.
--   - "Eletiva" (CCO) e "Optativa" (ECO) são vagas na grade, não matérias.
--
-- ch_teorica_disciplina + ch_pratica_disciplina dão a carga total (coluna
-- gerada). Onde a grade só informa o total do módulo, a carga foi distribuída
-- para fechar esse total. A divisão teórica/prática é uma estimativa:
-- laboratórios, extensão, projetos e estágios são 100% práticos.
-- ementa_disciplina fica NULL: pode ser cadastrada depois.
--
-- Código: mnemônico de até 10 caracteres.

INSERT INTO tb_disciplina
    (codigo_disciplina, nome_disciplina, ch_teorica_disciplina, ch_pratica_disciplina)
VALUES
    -- Comuns a CCO e ECO (25)
    ('ALP1', 'Algoritmos e Programação de Computadores I',  40, 20),
    ('ALP2', 'Algoritmos e Programação de Computadores II', 40, 20),
    ('CAL1', 'Cálculo I',                                   90,  0),
    ('CAL2', 'Cálculo II',                                  60,  0),
    ('SDG',  'Sistemas Digitais',                           40, 20),
    ('BD1',  'Banco de Dados I',                            40, 20),
    ('AOC',  'Arquitetura e Organização de Computadores',   40, 20),
    ('ED',   'Estrutura de Dados',                          40, 20),
    ('POO',  'Programação Orientada a Objetos',             40, 20),
    ('PES',  'Probabilidade e Estatística',                 60,  0),
    ('CNU',  'Cálculo Numérico',                            60,  0),
    ('ANA',  'Análise de Algoritmos',                       60,  0),
    ('ESW',  'Engenharia de Software',                      40, 20),
    ('SO',   'Sistemas Operacionais',                       40, 20),
    ('IA1',  'Inteligência Artificial',                     40, 20),
    ('CGR',  'Computação Gráfica',                          40, 20),
    ('PLP',  'Paradigmas de Linguagens de Programação',     60,  0),
    ('PDM',  'Programação para Dispositivos Móveis',        30, 30),
    ('TWB',  'Tecnologias Web',                             30, 30),
    ('RC1',  'Redes de Computadores I',                     40, 20),
    ('TGR',  'Teoria dos Grafos',                           60,  0),
    ('LFA',  'Linguagens Formais e Autômatos',              60,  0),
    ('SDI',  'Sistemas Distribuídos',                       40, 20),
    ('CMP',  'Compiladores',                                40, 20),
    ('TCO',  'Tópicos em Computação',                       60,  0),

    -- Só Ciência da Computação (31)
    ('TMA',  'Tópicos de Matemática',                       60,  0),
    ('AEX1', 'Atividade de Extensão I',                      0, 30),
    ('AEX2', 'Atividade de Extensão II',                     0, 30),
    ('AEX3', 'Atividade de Extensão III',                    0, 30),
    ('AEX4', 'Atividade de Extensão IV',                     0, 30),
    ('AEX5', 'Atividade de Extensão V',                      0, 30),
    ('FLG',  'Fundamentos de Lógica',                       60,  0),
    ('GAV',  'Geometria Analítica e Vetores',               60,  0),
    ('MDI',  'Matemática Discreta',                         60,  0),
    ('LP1',  'Laboratório de Práticas I',                    0, 60),
    ('LP2',  'Laboratório de Práticas II',                   0, 30),
    ('CSP',  'Cultura, Sociedade e Política',               60,  0),
    ('ALG',  'Álgebra Linear',                              60,  0),
    ('DHA',  'Direitos Humanos e Ambientais',               60,  0),
    ('TCP',  'Teoria da Computação',                        60,  0),
    ('PI2A', 'Projeto Integrador 2A',                        0, 90),
    ('BD2',  'Banco de Dados II',                           40, 20),
    ('GTI',  'Governança de TI e Mapeamento de Processos',  60,  0),
    ('PI3A', 'Projeto Integrador 3A',                        0, 30),
    ('PPA',  'Programação Paralela',                        40, 20),
    ('PI3B', 'Projeto Integrador 3B',                        0, 90),
    ('ELV',  'Eletiva',                                     60,  0),
    ('IA2',  'Inteligência Artificial II',                  40, 20),
    ('TBD',  'Tópicos em Banco de Dados',                   40, 20),
    ('EST1', 'Estágio Supervisionado I',                     0, 80),
    ('PGA',  'Projeto de Graduação CCO A',                  20, 60),
    ('PIM',  'Processamento de Imagens',                    40, 20),
    ('SCM',  'Sistemas de Comunicação',                     60,  0),
    ('STR',  'Sistemas de Tempo Real',                      40, 20),
    ('EST2', 'Estágio Supervisionado II',                    0, 80),
    ('PGB',  'Projeto de Graduação CCO B',                  20, 60),

    -- Só Engenharia de Computação (36)
    ('PEN',  'Práticas de Engenharia',                      30, 30),
    ('LCA',  'Laboratório de Circuitos Analógicos',          0, 30),
    ('QMA',  'Química e Materiais',                         40, 20),
    ('EMC',  'Estruturas Matemáticas para Computação',      60,  0),
    ('FCC',  'Fundamentos de Cálculo para Computação e Engenharia', 60, 0),
    ('SCD',  'Sociedade, Cultura, Direitos Humanos e Ambientais',   60, 0),
    ('ALA',  'Álgebra Linear e Aplicações',                 60,  0),
    ('LSD',  'Laboratório de Sistemas Digitais',             0, 30),
    ('EGR',  'Expressão Gráfica',                           10, 20),
    ('EDG',  'Eletrônica Digital',                          40, 20),
    ('PIED', 'Projeto Integrador - Eletrônica Digital',      0, 30),
    ('PEE1', 'Projeto de Extensão na Educação Superior I',   0, 130),
    ('FEC',  'Física para Engenharia da Computação',        60,  0),
    ('CEL',  'Circuitos Elétricos',                         40, 20),
    ('MME',  'Métodos Matemáticos em Engenharia',           60,  0),
    ('PEE2', 'Projeto de Extensão na Educação Superior II',  0, 130),
    ('CAL3', 'Cálculo III',                                 60,  0),
    ('ASI',  'Análise de Sinais',                           60,  0),
    ('EBA',  'Eletrônica Básica',                           40, 20),
    ('CEL2', 'Circuitos Elétricos II',                      40, 20),
    ('MSF',  'Mecânica dos Sólidos e Fenômenos de Transporte', 60, 0),
    ('SLI',  'Sistemas Lineares',                           60,  0),
    ('SEM',  'Sistemas Embarcados',                         40, 20),
    ('PISE', 'Projeto Integrador - Sistemas Embarcados',     0, 30),
    ('PEE3', 'Projeto de Extensão na Educação Superior III', 0, 130),
    ('ADE',  'Administração e Economia',                    60,  0),
    ('PDS',  'Processamento Digital de Sinais',             40, 20),
    ('MCS',  'Modelagem e Controle de Sistemas',            60,  0),
    ('TCC1', 'Trabalho de Conclusão de Curso I - Eng Comp', 20, 40),
    ('PSM',  'Processamento de Sinais Multimídia',          40, 20),
    ('ESA',  'Estágio Supervisionado - Aplicação Profissional',  0, 80),
    ('OPT',  'Optativa',                                    60,  0),
    ('TIC',  'Teoria da Informação e Codificação',          60,  0),
    ('TCC2', 'Trabalho de Conclusão de Curso II - Eng Comp', 20, 40),
    ('ESI',  'Estágio Supervisionado - Integração Profissional', 0, 80),
    ('MDD',  'Mineração de Dados',                          40, 20);

-- ============================================================
-- CURRICULO_DISCIPLINA
-- ============================================================

-- Composição de cada grade: em que semestre da GRADE (1, 2, 3...) cada
-- disciplina aparece. Não confundir com periodo_letivo, que é o semestre de
-- calendário. Cada linha do VALUES é um módulo da grade:
--   CCO: 1A=1, 1B=2, 2A=3, 2B=4, 3A=5, 3B=6, 4A=7, 4B=8
--   ECO: mesma regra, até 5B=10.
--
-- Tudo é 'obrigatoria', exceto as vagas de escolha: 'Eletiva' (CCO) é
-- 'eletiva' e 'Optativa' (ECO) é 'optativa'.
--
-- Um código com erro de digitação não some em silêncio: o subselect devolve
-- NULL e a coluna id_disciplina (NOT NULL) rejeita a linha.

INSERT INTO tb_curriculo_disciplina
    (id_curriculo, id_disciplina, periodo_curriculo_disciplina, tipo_curriculo_disciplina)
SELECT
    (SELECT k.id_curriculo
       FROM tb_curriculo k JOIN tb_curso c ON c.id_curso = k.id_curso
      WHERE c.codigo_curso = m.curso),
    (SELECT d.id_disciplina FROM tb_disciplina d WHERE d.codigo_disciplina = u.codigo),
    m.periodo,
    (CASE u.codigo
         WHEN 'ELV' THEN 'eletiva'
         WHEN 'OPT' THEN 'optativa'
         ELSE 'obrigatoria'
     END)::tipo_disc_t
FROM (VALUES
    -- Ciência da Computação (grade 2023/1) — 56 disciplinas
    ('CCO', 1, ARRAY['TMA','ALP1','AEX1','FLG','GAV','MDI','LP1','CSP']),
    ('CCO', 2, ARRAY['CAL1','ALP2','ALG','AEX2','BD1','DHA','SDG','LP2']),
    ('CCO', 3, ARRAY['CAL2','AOC','AEX3','ED','PI2A','TCP']),
    ('CCO', 4, ARRAY['BD2','ESW','IA1','POO','SO','GTI']),
    ('CCO', 5, ARRAY['AEX4','CNU','CGR','PLP','PDM','PI3A','TWB','PES']),
    ('CCO', 6, ARRAY['AEX5','LFA','PPA','PI3B','RC1','TGR']),
    ('CCO', 7, ARRAY['ANA','ELV','IA2','SDI','TBD','EST1','PGA']),
    ('CCO', 8, ARRAY['CMP','PIM','SCM','STR','TCO','EST2','PGB']),
    -- Engenharia de Computação — 61 disciplinas
    ('ECO', 1,  ARRAY['PEN','LCA','QMA','ALP1','EMC','FCC','SCD']),
    ('ECO', 2,  ARRAY['SDG','CAL1','ALP2','ALA','BD1','LSD','EGR']),
    ('ECO', 3,  ARRAY['EDG','PIED','PEE1','AOC','CAL2','ED','FEC']),
    ('ECO', 4,  ARRAY['CEL','MME','PEE2','CAL3','PES','POO']),
    ('ECO', 5,  ARRAY['ASI','EBA','CEL2','CNU','MSF','ANA']),
    ('ECO', 6,  ARRAY['SLI','SEM','PISE','PEE3','IA1','CGR','ADE']),
    ('ECO', 7,  ARRAY['PDS','MCS','ESW','PDM','PLP']),
    ('ECO', 8,  ARRAY['TWB','RC1','TGR','LFA','SO']),
    ('ECO', 9,  ARRAY['TCC1','PSM','ESA','OPT','SDI']),
    ('ECO', 10, ARRAY['TIC','TCC2','ESI','TCO','CMP','MDD'])
) AS m(curso, periodo, codigos)
CROSS JOIN LATERAL unnest(m.codigos) AS u(codigo);

-- ============================================================
-- PRE_REQUISITO
-- ============================================================

-- Fonte: "Tabela de Pré-Requisitos" de CCO e de Engenharia de Computação.
-- Leitura de cada linha: (disciplina, requisito, vínculo) = a disciplina exige
-- o requisito. Regras de transcrição:
--   - "deve ser cursado junto com" e "(matr)"  -> co_requisito
--   - os demais                                -> pre_requisito
--   - um requisito que aparece nas duas tabelas é escrito uma vez só abaixo
--
-- Fica de fora o que não é "disciplina exige disciplina":
--   - "75% CH concluída" (Tópicos em Computação) e a regra de 75% das
--     disciplinas teóricas para TCC e Projeto de Graduação. É uma regra sobre o
--     histórico do aluno, não uma relação entre duas disciplinas. Fica para a
--     aplicação/consulta.
--   - AMM, Automação e Robótica, Princípios de Controle e Projeto Integrador 3A
--     de Engenharia: a tabela os cita, mas não estão na matriz curricular de
--     Engenharia usada no catálogo.
--
-- pre_requisito é por currículo (modelo v3). Cada linha da lista abaixo vira
-- uma exigência em todo currículo que tem as duas disciplinas na grade; a
-- coluna "curso" restringe a um curso só. Duas disciplinas têm exigência
-- diferente em cada curso:
--   Sistemas Digitais:      CCO exige Fund. de Lógica; ECO exige Práticas de Eng.
--   Linguagens Formais:     CCO exige Teoria da Computação; ECO exige Estr. de Dados.
-- Sem a restrição, LFA <- ED valeria também em CCO, porque Estrutura de Dados
-- está na grade de CCO.
--
-- A lista fica numa tabela temporária para a conferência do fim do bloco
-- poder checar que toda linha virou pelo menos uma exigência.
--
-- As cadeias mais longas, só de pre_requisito, têm 4 níveis, ex.:
-- Compiladores -> Linguagens Formais -> Estrutura de Dados -> Algoritmos II ->
-- Algoritmos I.

CREATE TEMP TABLE pre_requisito_fonte (
    disciplina varchar(10) NOT NULL,
    requisito  varchar(10) NOT NULL,
    vinculo    vinculo_t   NOT NULL,
    curso      varchar(10)            -- NULL = vale em todo currículo
) ON COMMIT DROP;

INSERT INTO pre_requisito_fonte (disciplina, requisito, vinculo, curso) VALUES
    -- Tabela de CCO
    ('ALG',  'GAV',  'pre_requisito', NULL),
    ('ANA',  'ED',   'pre_requisito', NULL),
    ('ALP2', 'ALP1', 'pre_requisito', NULL),
    ('AOC',  'SDG',  'pre_requisito', NULL),
    ('BD1',  'MDI',  'pre_requisito', NULL),
    ('BD2',  'BD1',  'pre_requisito', NULL),
    ('CNU',  'CAL2', 'pre_requisito', NULL),
    ('CAL1', 'TMA',  'pre_requisito', NULL),
    ('CAL2', 'CAL1', 'pre_requisito', NULL),
    ('CMP',  'LFA',  'pre_requisito', NULL),
    ('CGR',  'CAL1', 'pre_requisito', NULL),
    ('CGR',  'ALG',  'pre_requisito', NULL),
    ('ESW',  'BD1',  'pre_requisito', NULL),
    ('ED',   'ALP2', 'pre_requisito', NULL),
    ('IA1',  'ALP2', 'pre_requisito', NULL),
    ('IA2',  'IA1',  'pre_requisito', NULL),
    ('LFA',  'TCP',  'pre_requisito', 'CCO'),
    ('PDM',  'POO',  'pre_requisito', NULL),
    ('PDM',  'ED',   'pre_requisito', NULL),
    ('PLP',  'ED',   'pre_requisito', NULL),
    ('POO',  'ALP2', 'pre_requisito', NULL),
    ('PES',  'CAL1', 'pre_requisito', NULL),
    ('PIM',  'CAL2', 'pre_requisito', NULL),
    ('PPA',  'ED',   'pre_requisito', NULL),
    ('PI2A', 'ED',   'co_requisito', NULL),
    ('PI3A', 'PDM',  'co_requisito', NULL),
    ('PI3B', 'TGR',  'co_requisito', NULL),
    ('RC1',  'PES',  'pre_requisito', NULL),
    ('SCM',  'PES',  'pre_requisito', NULL),
    ('SCM',  'ALG',  'pre_requisito', NULL),
    ('SDG',  'FLG',  'pre_requisito', 'CCO'),
    ('SDI',  'SO',   'pre_requisito', NULL),
    ('STR',  'ED',   'pre_requisito', NULL),
    ('SO',   'ALP2', 'pre_requisito', NULL),
    ('TCP',  'FLG',  'pre_requisito', NULL),
    ('TGR',  'ED',   'pre_requisito', NULL),
    ('TBD',  'BD2',  'pre_requisito', NULL),
    -- Tabela de Engenharia de Computação (só o que não repete a de CCO)
    ('ASI',  'MME',  'pre_requisito', NULL),
    ('CAL3', 'CAL2', 'pre_requisito', NULL),
    ('CEL',  'PEN',  'pre_requisito', NULL),
    ('CEL2', 'CEL',  'pre_requisito', NULL),
    ('CEL2', 'MME',  'pre_requisito', NULL),
    ('EDG',  'SDG',  'pre_requisito', NULL),
    ('EBA',  'CEL',  'pre_requisito', NULL),
    ('LFA',  'ED',   'pre_requisito', 'ECO'),
    ('MME',  'CAL2', 'co_requisito', NULL),
    ('PDS',  'SLI',  'pre_requisito', NULL),
    ('PIED', 'EDG',  'co_requisito', NULL),
    ('PSM',  'PDS',  'pre_requisito', NULL),
    ('SDG',  'PEN',  'pre_requisito', 'ECO'),
    ('SLI',  'ASI',  'pre_requisito', NULL),
    ('TIC',  'SLI',  'pre_requisito', NULL);

INSERT INTO tb_pre_requisito
    (id_curriculo, id_disciplina, id_disciplina_requisito, vinculo_pre_requisito)
SELECT
    cd.id_curriculo,
    cd.id_disciplina,
    rq.id_disciplina,
    f.vinculo
FROM pre_requisito_fonte f
JOIN tb_disciplina d ON d.codigo_disciplina = f.disciplina
JOIN tb_disciplina r ON r.codigo_disciplina = f.requisito
JOIN tb_curriculo_disciplina cd ON cd.id_disciplina = d.id_disciplina
JOIN tb_curriculo_disciplina rq
  ON rq.id_curriculo  = cd.id_curriculo
 AND rq.id_disciplina = r.id_disciplina
JOIN tb_curriculo cu ON cu.id_curriculo = cd.id_curriculo
JOIN tb_curso c      ON c.id_curso      = cu.id_curso
WHERE f.curso IS NULL OR f.curso = c.codigo_curso;

-- Conferência: a ordem dos semestres envolve duas linhas de
-- curriculo_disciplina e não cabe em constraint. Se a carga violar alguma
-- regra, o script para aqui em vez de seguir com dados incoerentes.
-- (Que disciplina e requisito estão na mesma grade, as FKs compostas já
-- garantem.)
--   1. pre_requisito: o requisito vem em semestre anterior da grade;
--   2. co_requisito: o requisito vem no mesmo semestre ou antes;
--   3. toda linha da lista virou pelo menos uma exigência (senão seria
--      letra morta, ex.: código digitado errado).

DO $$
DECLARE
    violacoes integer;
BEGIN
    SELECT count(*) INTO violacoes
    FROM tb_pre_requisito p
    JOIN tb_curriculo_disciplina cd
      ON cd.id_curriculo  = p.id_curriculo
     AND cd.id_disciplina = p.id_disciplina
    JOIN tb_curriculo_disciplina rq
      ON rq.id_curriculo  = p.id_curriculo
     AND rq.id_disciplina = p.id_disciplina_requisito
    WHERE p.vinculo_pre_requisito = 'pre_requisito'
      AND rq.periodo_curriculo_disciplina >= cd.periodo_curriculo_disciplina;
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % pre_requisito(s) com requisito em semestre igual ou posterior', violacoes;
    END IF;

    SELECT count(*) INTO violacoes
    FROM tb_pre_requisito p
    JOIN tb_curriculo_disciplina cd
      ON cd.id_curriculo  = p.id_curriculo
     AND cd.id_disciplina = p.id_disciplina
    JOIN tb_curriculo_disciplina rq
      ON rq.id_curriculo  = p.id_curriculo
     AND rq.id_disciplina = p.id_disciplina_requisito
    WHERE p.vinculo_pre_requisito = 'co_requisito'
      AND rq.periodo_curriculo_disciplina > cd.periodo_curriculo_disciplina;
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % co_requisito(s) com requisito em semestre posterior', violacoes;
    END IF;

    SELECT count(*) INTO violacoes
    FROM pre_requisito_fonte f
    WHERE NOT EXISTS (
        SELECT 1
        FROM tb_pre_requisito p
        JOIN tb_disciplina d ON d.id_disciplina = p.id_disciplina
        JOIN tb_disciplina r ON r.id_disciplina = p.id_disciplina_requisito
        WHERE d.codigo_disciplina = f.disciplina
          AND r.codigo_disciplina = f.requisito
    );
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % linha(s) da lista de pré-requisitos sem nenhuma grade', violacoes;
    END IF;
END
$$;

-- ============================================================
-- TURMA
-- ============================================================

-- Uma turma é a oferta de uma disciplina num período letivo. Para cada um dos
-- 4 semestres gera-se a oferta do módulo daquele semestre, para cada coorte:
--
--   semestre   módulo   (n = periodo_curriculo_disciplina)
--   2025/1     1A       n = 1
--   2025/2     1B       n = 2
--   2026/1     2A       n = 3
--   2026/2     2B       n = 4    <- semestre corrente
--
-- Coortes (um grupo de alunos que sobe junto, módulo a módulo):
--   CCODM - Ciência da Computação, matutino  (Campus Sul)
--   CCONM - Ciência da Computação, noturno   (Campus Sul)
--   ECONM - Engenharia de Computação, noturno (Campus Ceilândia)
-- O código segue o padrão do enunciado (CCODM2B, CCONM2B): curso + D(iurno) ou
-- N(oturno) + M(ódulo) + módulo, e o sufixo identifica a disciplina, já que
-- cada turma deste modelo é a oferta de uma disciplina só.
-- Ex.: CCODM2B-BD2 = Banco de Dados II da turma CCODM2B em 2026/2.
--
-- Professor: rodízio determinístico pela disciplina, deslocado por coorte para
-- uma mesma disciplina ter professores diferentes nas coortes (ver conferência).
--
-- vagas_turma:
--   - semestres encerrados: 45;
--   - 2026/2: 41 (coorte de 40 alunos + 1). Cada turma de 2026/2 tem
--     exatamente 1 vaga livre, a "última vaga" que a frente de concorrência do
--     Marco 2 disputa. COUNT(matricula) <= vagas_turma NÃO é constraint: é
--     garantida por transação.

INSERT INTO tb_turma
    (codigo_turma, id_disciplina, id_periodo_letivo, id_professor, turno_turma, vagas_turma)
SELECT
    format('%s%sM%s%s-%s',
           co.curso, co.letra, (cd.n + 1) / 2, CASE cd.n % 2 WHEN 1 THEN 'A' ELSE 'B' END,
           d.codigo_disciplina),
    d.id_disciplina,
    pl.id_periodo_letivo,
    pr.id_professor,
    co.turno::turno_t,
    CASE WHEN pl.ano_periodo_letivo = 2026 AND pl.semestre_periodo_letivo = 2 THEN 41 ELSE 45 END
FROM (VALUES
    ('CCO', 'D', 'matutino', 0),
    ('CCO', 'N', 'noturno',  4),
    ('ECO', 'N', 'noturno',  6)
) AS co(curso, letra, turno, deslocamento)
JOIN tb_curso c ON c.codigo_curso = co.curso
JOIN tb_curriculo k ON k.id_curso = c.id_curso
JOIN (SELECT id_curriculo, id_disciplina,
             periodo_curriculo_disciplina AS n
        FROM tb_curriculo_disciplina
       WHERE periodo_curriculo_disciplina <= 4) cd ON cd.id_curriculo = k.id_curriculo
JOIN tb_disciplina d ON d.id_disciplina = cd.id_disciplina
JOIN tb_periodo_letivo pl
  ON (pl.ano_periodo_letivo - 2025) * 2 + pl.semestre_periodo_letivo = cd.n
JOIN (SELECT id_professor,
             row_number() OVER (ORDER BY matricula_professor) - 1 AS rn
        FROM tb_professor) pr
  ON pr.rn = (d.id_disciplina + co.deslocamento) % 12;

-- ============================================================
-- TURMA_HORARIO
-- ============================================================

-- Só as turmas de 2026/2 recebem horário: a grade dos semestres encerrados
-- não é usada por nenhuma consulta. Turma sem horário é válida no modelo.
-- id_periodo_letivo vem da própria turma (a FK composta
-- fk_turma_horario_turma exige isso), e o EXCLUDE usa essa coluna para
-- liberar a mesma sala e faixa em outro semestre.
--
-- Faixas (semiabertas [), aula que termina às 09:10 não conflita com a que
-- começa às 09:10):
--   matutino: 07:30-09:10 | 09:20-11:00 | 11:10-12:50, de segunda a sexta
--             (15 faixas por semana)
--   noturno:  19:00-20:40 | 20:50-22:30, de segunda a sexta, mais sábado de
--             manhã 08:00-09:40 | 09:50-11:30 (12 faixas por semana)
--
-- Cada disciplina ocupa 2 faixas seguidas (60 h ~ 4 h/semana). A coorte tem 6
-- disciplinas em 2026/2, então usa 12 faixas distintas e nunca tem duas
-- aulas ao mesmo tempo.
--
-- Salas: cada coorte tem uma sala de aula fixa (sala comum do bloco) e usa o
-- laboratório nas disciplinas com parte prática de 20 h ou mais. Os horários
-- do matutino e do noturno não se cruzam, então a mesma sala serve aos dois
-- turnos. O EXCLUDE ex_turma_horario_sala_ocupada garante, de qualquer
-- forma, que não haja conflito.

INSERT INTO tb_turma_horario
    (id_turma, id_periodo_letivo, id_sala, dia_semana_turma_horario, faixa_turma_horario)
SELECT
    t.id_turma,
    t.id_periodo_letivo,
    s.id_sala,
    sl.dia,
    timerange(sl.inicio, sl.fim, '[)')
FROM (
    -- ordem da disciplina dentro da coorte (0..5) define quais faixas ela usa
    SELECT t.id_turma,
           t.id_periodo_letivo,
           t.turno_turma,
           left(t.codigo_turma, 3) AS curso,
           d.ch_pratica_disciplina,
           row_number() OVER (PARTITION BY split_part(t.codigo_turma, '-', 1)
                              ORDER BY d.id_disciplina) - 1 AS j
      FROM tb_turma t
      JOIN tb_periodo_letivo pl ON pl.id_periodo_letivo = t.id_periodo_letivo
      JOIN tb_disciplina d ON d.id_disciplina = t.id_disciplina
     WHERE pl.ano_periodo_letivo = 2026 AND pl.semestre_periodo_letivo = 2
) t
CROSS JOIN generate_series(0, 1) AS k(k)
JOIN (
    SELECT 'matutino'::turno_t AS turno, i AS idx, i / 3 + 1 AS dia,
           (ARRAY['07:30','09:20','11:10'])[i % 3 + 1]::time AS inicio,
           (ARRAY['09:10','11:00','12:50'])[i % 3 + 1]::time AS fim
      FROM generate_series(0, 14) AS i
    UNION ALL
    SELECT 'noturno'::turno_t, i, i / 2 + 1,
           (CASE WHEN i / 2 + 1 = 6 THEN (ARRAY['08:00','09:50'])[i % 2 + 1]
                 ELSE (ARRAY['19:00','20:50'])[i % 2 + 1] END)::time,
           (CASE WHEN i / 2 + 1 = 6 THEN (ARRAY['09:40','11:30'])[i % 2 + 1]
                 ELSE (ARRAY['20:40','22:30'])[i % 2 + 1] END)::time
      FROM generate_series(0, 11) AS i
) sl ON sl.turno = t.turno_turma AND sl.idx = 2 * t.j + k.k
JOIN tb_curso c ON c.codigo_curso = t.curso
JOIN tb_sala s
  ON s.id_campus = c.id_campus
 AND s.codigo_sala = CASE
         WHEN t.ch_pratica_disciplina >= 20
             THEN CASE t.curso WHEN 'CCO' THEN 'KA1' ELSE 'EA1' END
         ELSE CASE t.curso WHEN 'CCO' THEN 'JB3' ELSE 'DB3' END
     END;

-- Conferência: duas regras que o EXCLUDE não cobre (ele só olha a sala).
--   1. nenhum professor em duas turmas ao mesmo tempo, no mesmo semestre;
--   2. a sala comporta as vagas da turma.

DO $$
DECLARE
    violacoes integer;
BEGIN
    SELECT count(*) INTO violacoes
    FROM tb_turma_horario h1
    JOIN tb_turma t1 ON t1.id_turma = h1.id_turma
    JOIN tb_turma_horario h2
      ON h2.id_turma_horario > h1.id_turma_horario
     AND h2.id_periodo_letivo = h1.id_periodo_letivo
     AND h2.dia_semana_turma_horario = h1.dia_semana_turma_horario
     AND h2.faixa_turma_horario && h1.faixa_turma_horario
    JOIN tb_turma t2 ON t2.id_turma = h2.id_turma
    WHERE t1.id_professor = t2.id_professor;
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % choque(s) de horário de professor', violacoes;
    END IF;

    SELECT count(*) INTO violacoes
    FROM tb_turma_horario h
    JOIN tb_turma t ON t.id_turma = h.id_turma
    JOIN tb_sala s ON s.id_sala = h.id_sala
    WHERE s.capacidade_sala < t.vagas_turma;
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % horário(s) em sala menor que as vagas da turma', violacoes;
    END IF;
END
$$;

-- ============================================================
-- ALUNO
-- ============================================================

-- 120 alunos, 40 por coorte, todos ingressantes em 2025/1:
--   id_aluno   1..40   -> CCODM (Ciência da Computação, matutino)
--   id_aluno  41..80   -> CCONM (Ciência da Computação, noturno)
--   id_aluno  81..120  -> ECONM (Engenharia de Computação, noturno)
-- A coorte é (id_aluno - 1) / 40, e o bloco de matrículas usa essa mesma
-- conta. A ordem do INSERT é fixa (ORDER BY) para os ids saírem sequenciais.
--
-- Tudo é sintético e determinístico:
--   - nome: primeiro + nome do meio + sobrenome, de três listas. O primeiro
--     (30 opções) e o último (31, número primo com 30) combinam com
--     i mod 30 e i mod 31, então o par primeiro/último nunca se repete
--     nos 120 alunos.
--   - e-mail: primeiro.ultimo@iesb.edu.br, em minúsculas e sem acento
--     (ck_aluno_email_minusculo exige minúsculas). Ex.: Ana Alves Almeida ->
--     ana.almeida@iesb.edu.br. Como o par primeiro/último é único, o e-mail
--     também é.
--   - matrícula: '20251' + número com 4 dígitos (ingresso em 2025/1).
--   - CPF: 11 dígitos com zeros à esquerda (00000000001, ...). É inválido por
--     construção (a base 000000000 só tem DV 00), então nunca coincide com um
--     CPF real. O banco só confere o formato (ck_aluno_cpf_valido), não o DV.
--   - nascimento: 2005 a 2007, com 1 em cada 9 alunos mais velho (~10 anos),
--     para haver variedade de idade.
--
-- id_curso e id_curriculo saem do mesmo currículo, o que satisfaz a FK
-- composta fk_aluno_curriculo_curso (o currículo pertence ao curso do aluno).

INSERT INTO tb_aluno
    (matricula_aluno, nome_aluno, cpf_aluno, email_aluno, nascimento_aluno,
     id_curso, id_curriculo, ingresso_aluno)
WITH nomes AS (
    SELECT
        ARRAY['Ana','Bruno','Camila','Daniel','Eduarda','Felipe','Gabriela','Heitor',
              'Isabela','João','Karina','Lucas','Mariana','Nicolas','Olívia','Pedro',
              'Rafaela','Samuel','Tatiane','Vinícius','Yasmin','Arthur','Beatriz',
              'Caio','Diego','Elisa','Fernando','Giovana','Igor','Júlia'] AS primeiros,
        ARRAY['Alves','Barros','Cardoso','Dias','Duarte','Farias','Gomes','Lacerda',
              'Macedo','Machado','Matos','Mendes','Moreira','Nascimento','Nunes',
              'Oliveira','Pacheco','Pereira','Ramos','Ribeiro','Rocha','Santana',
              'Teixeira','Vasconcelos','Xavier'] AS meios,
        ARRAY['Almeida','Araújo','Azevedo','Batista','Borges','Brandão','Campos',
              'Castro','Coelho','Correia','Costa','Cunha','Fernandes','Ferreira',
              'Fonseca','Guimarães','Lima','Lopes','Marques','Martins','Medeiros',
              'Miranda','Monteiro','Moraes','Pinto','Ramalho','Rodrigues','Sampaio',
              'Silveira','Tavares','Viana'] AS ultimos
)
SELECT
    '20251' || lpad(g.i::text, 4, '0'),
    n.primeiros[(g.i - 1) % 30 + 1] || ' ' ||
        n.meios[(g.i * 7) % 25 + 1] || ' ' ||
        n.ultimos[(g.i - 1) % 31 + 1],
    lpad(g.i::text, 11, '0'),
    translate(lower(n.primeiros[(g.i - 1) % 30 + 1] || '.' || n.ultimos[(g.i - 1) % 31 + 1]),
              'áàâãäéèêëíìîïóòôõöúùûüçñ', 'aaaaaeeeeiiiiooooouuuucn')
        || '@iesb.edu.br',
    DATE '2005-01-01' + ((g.i * 37) % 1000) - CASE WHEN g.i % 9 = 0 THEN 3650 ELSE 0 END,
    k.id_curso,
    k.id_curriculo,
    DATE '2025-02-03'
FROM generate_series(1, 120) AS g(i)
CROSS JOIN nomes n
JOIN (VALUES (0, 'CCO'), (1, 'CCO'), (2, 'ECO')) AS co(coorte, curso)
  ON co.coorte = (g.i - 1) / 40
JOIN tb_curso c ON c.codigo_curso = co.curso
JOIN tb_curriculo k ON k.id_curso = c.id_curso
ORDER BY g.i;

-- ============================================================
-- MATRICULA
-- ============================================================

-- Cada aluno cursa, em cada semestre, as turmas do módulo da sua coorte:
-- 28 matrículas em CCO (8+8+6+6) e 27 em ECO (7+7+7+6), ou seja,
-- 80 x 28 + 40 x 27 = 3.320 matrículas.
--
-- Coorte do aluno = (id_aluno - 1) / 40, a mesma conta do bloco de alunos; o
-- prefixo do código da turma (CCODM, CCONM, ECONM) liga o aluno às turmas.
--
-- Status:
--   - 2026/2 (corrente): todas 'ativa'. Cada turma fica com 40 matrículas
--     ativas e 41 vagas, ou seja, 1 vaga livre: a "última vaga" do Marco 2.
--   - semestres encerrados: 'concluida', salvo cerca de 1 em 97, que é
--     'trancada' (escolhido por uma conta fixa sobre aluno e turma, não por
--     sorteio). 'cancelada' não aparece na carga.
--
-- Não há repetência: cada aluno cursa o módulo de cada semestre uma vez, mesmo
-- que tenha reprovado ou trancado alguma disciplina.
--
-- data_matricula: entre 5 e 18 dias antes do início do período, em horário de
-- Brasília (timestamptz). Todas no passado, como exige
-- ck_matricula_data_nao_futura.
-- UNIQUE (id_aluno, id_turma) é satisfeita: cada par aparece uma vez.

INSERT INTO tb_matricula (id_aluno, id_turma, data_matricula, status_matricula)
SELECT
    a.id_aluno,
    t.id_turma,
    ((pl.data_inicio_periodo_letivo - (5 + a.id_aluno % 14)) + time '08:00'
        + (a.id_aluno % 9) * interval '1 hour') AT TIME ZONE 'America/Sao_Paulo',
    (CASE
         WHEN pl.ano_periodo_letivo = 2026 AND pl.semestre_periodo_letivo = 2 THEN 'ativa'
         WHEN (a.id_aluno * 31 + t.id_turma * 17) % 97 = 0 THEN 'trancada'
         ELSE 'concluida'
     END)::status_mat_t
FROM tb_aluno a
JOIN (VALUES (0, 'CCODM'), (1, 'CCONM'), (2, 'ECONM')) AS co(coorte, prefixo)
  ON co.coorte = (a.id_aluno - 1) / 40
JOIN tb_turma t ON left(t.codigo_turma, 5) = co.prefixo
JOIN tb_periodo_letivo pl ON pl.id_periodo_letivo = t.id_periodo_letivo
ORDER BY a.id_aluno, pl.ano_periodo_letivo, pl.semestre_periodo_letivo, t.id_turma;

-- ============================================================
-- HISTORICO
-- ============================================================

-- Uma linha por matrícula (relação 1:1, uq_historico_matricula). Notas e
-- frequência saem de um hash fixo de (aluno, turma), sem random():
--
--   concluida: A1 e A2 entre 4,0 e 10,0. Se a média de A1 e A2 ficar abaixo de
--              6, 3 em cada 4 alunos fazem a P3 (entre 5,0 e 10,0), que
--              substitui a menor nota. Frequência entre 72 e 100.
--   ativa:     semestre em curso, só a A1 lançada e frequência parcial. A2 e P3
--              ficam NULL, então media_final_historico é NULL (ausência não é
--              zero) e a situação é 'cursando'.
--   trancada:  sem notas, frequência baixa, situação 'trancada'.
--
-- media_final_historico é coluna gerada e não é inserida. A situação das
-- matrículas concluídas é calculada logo abaixo, a partir da média que o
-- próprio banco gerou. Assim a regra de cálculo não é duplicada aqui.

INSERT INTO tb_historico
    (id_matricula, nota_a1_historico, nota_a2_historico, nota_p3_historico,
     frequencia_historico, situacao_historico)
WITH base AS (
    SELECT m.id_matricula,
           m.status_matricula AS st,
           (m.id_aluno * 7919 + m.id_turma * 104729) % 1000003 AS h
      FROM tb_matricula m
),
notas AS (
    SELECT id_matricula, st, h,
           CASE WHEN st = 'trancada' THEN NULL
                ELSE (4 + (h % 61) / 10.0)::numeric(4,2) END AS a1,
           CASE WHEN st = 'concluida'
                THEN (4 + ((h / 61) % 61) / 10.0)::numeric(4,2) END AS a2
      FROM base
)
SELECT
    id_matricula,
    a1,
    a2,
    CASE WHEN st = 'concluida' AND a1 * 0.4 + a2 * 0.6 < 6 AND h % 4 <> 0
         THEN (5 + ((h / 3721) % 51) / 10.0)::numeric(4,2) END,
    (CASE st
         WHEN 'concluida' THEN 72 + ((h / 227) % 29)
         WHEN 'ativa'     THEN 85 + ((h / 227) % 16)
         ELSE                  30 + ((h / 227) % 40)
     END)::numeric(5,2),
    (CASE st WHEN 'trancada' THEN 'trancada' ELSE 'cursando' END)::situacao_t
FROM notas
ORDER BY id_matricula;

-- Situação das matrículas concluídas: aprovado com média >= 6 e frequência
-- >= 75; reprovação por nota, por falta ou pelas duas (reprovado_nota_falta).

UPDATE tb_historico h
   SET situacao_historico = (CASE
           WHEN h.media_final_historico >= 6 AND h.frequencia_historico >= 75 THEN 'aprovado'
           WHEN h.media_final_historico <  6 AND h.frequencia_historico >= 75 THEN 'reprovado_nota'
           WHEN h.media_final_historico >= 6                                  THEN 'reprovado_falta'
           ELSE 'reprovado_nota_falta'
       END)::situacao_t
  FROM tb_matricula m
 WHERE m.id_matricula = h.id_matricula
   AND m.status_matricula = 'concluida';

-- ============================================================
-- LOG_MATRICULA
-- ============================================================

-- Trilha de auditoria. Um evento 'criada' por matrícula (no instante do
-- INSERT, com o estado inicial 'ativa'), mais um 'trancada' para cada
-- matrícula trancada. usuario_log_matricula fica com o DEFAULT (current_user).
--
-- A última linha é de propósito: um evento que aponta para uma matrícula que
-- não existe mais. log_matricula não tem FK em id_matricula, e é por isso que
-- o log consegue guardar a remoção que a auditoria precisa registrar.

INSERT INTO tb_log_matricula
    (id_matricula, acao_log_matricula, ocorrido_em_log_matricula, detalhe_log_matricula)
SELECT id_matricula, acao, quando, detalhe
FROM (
    SELECT m.id_matricula,
           'criada' AS acao,
           m.data_matricula AS quando,
           jsonb_build_object('id_aluno', m.id_aluno, 'id_turma', m.id_turma,
                              'status', 'ativa', 'origem', 'carga') AS detalhe
      FROM tb_matricula m
    UNION ALL
    SELECT m.id_matricula,
           'trancada',
           ((pl.data_inicio_periodo_letivo + 30) + time '10:00') AT TIME ZONE 'America/Sao_Paulo',
           jsonb_build_object('status_anterior', 'ativa', 'status_novo', 'trancada',
                              'origem', 'carga')
      FROM tb_matricula m
      JOIN tb_turma t ON t.id_turma = m.id_turma
      JOIN tb_periodo_letivo pl ON pl.id_periodo_letivo = t.id_periodo_letivo
     WHERE m.status_matricula = 'trancada'
) ev
ORDER BY id_matricula, quando;

INSERT INTO tb_log_matricula
    (id_matricula, acao_log_matricula, ocorrido_em_log_matricula, detalhe_log_matricula)
SELECT max(id_matricula) + 1000,
       'removida',
       TIMESTAMPTZ '2026-03-10 14:00:00-03',
       jsonb_build_object('motivo', 'matrícula duplicada removida pela secretaria',
                          'origem', 'carga')
  FROM tb_matricula;

-- ============================================================
-- CONFERÊNCIA FINAL
-- ============================================================

-- Sequences: nenhum id foi inserido na mão, então as sequences das colunas
-- IDENTITY já estão à frente dos dados e não precisam de setval.
--
-- Confere os mínimos do enunciado (100 alunos, 6 turmas, 300 matrículas) e as
-- propriedades que o resto do projeto assume. Se algo falhar, a carga para
-- aqui em vez de seguir com dados incoerentes.

DO $$
DECLARE
    n_alunos     integer;
    n_turmas     integer;
    n_matriculas integer;
    violacoes    integer;
BEGIN
    SELECT count(*) INTO n_alunos     FROM tb_aluno;
    SELECT count(*) INTO n_turmas     FROM tb_turma;
    SELECT count(*) INTO n_matriculas FROM tb_matricula;

    IF n_alunos < 100 OR n_turmas < 6 OR n_matriculas < 300 THEN
        RAISE EXCEPTION 'carga abaixo do mínimo do enunciado: % alunos, % turmas, % matrículas',
            n_alunos, n_turmas, n_matriculas;
    END IF;

    -- 1:1 entre matrícula e histórico
    SELECT count(*) INTO violacoes
      FROM tb_matricula m
     WHERE NOT EXISTS (SELECT 1 FROM tb_historico h WHERE h.id_matricula = m.id_matricula);
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % matrícula(s) sem histórico', violacoes;
    END IF;

    -- nenhuma turma passa das vagas (ativas + concluídas ocupam vaga)
    SELECT count(*) INTO violacoes
      FROM (SELECT t.id_turma
              FROM tb_turma t
              JOIN tb_matricula m ON m.id_turma = t.id_turma
               AND m.status_matricula IN ('ativa', 'concluida')
             GROUP BY t.id_turma, t.vagas_turma
            HAVING count(*) > t.vagas_turma) x;
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % turma(s) com mais matrículas que vagas', violacoes;
    END IF;

    -- cada turma de 2026/2 tem exatamente 1 vaga livre (cenário da última vaga)
    SELECT count(*) INTO violacoes
      FROM tb_turma t
      JOIN tb_periodo_letivo pl ON pl.id_periodo_letivo = t.id_periodo_letivo
     WHERE pl.ano_periodo_letivo = 2026 AND pl.semestre_periodo_letivo = 2
       AND t.vagas_turma - (SELECT count(*) FROM tb_matricula m
                             WHERE m.id_turma = t.id_turma
                               AND m.status_matricula = 'ativa') <> 1;
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % turma(s) de 2026/2 sem exatamente 1 vaga livre', violacoes;
    END IF;

    -- situação coerente com o estado da matrícula
    SELECT count(*) INTO violacoes
      FROM tb_historico h
      JOIN tb_matricula m ON m.id_matricula = h.id_matricula
     WHERE (m.status_matricula = 'concluida'
            AND (h.media_final_historico IS NULL
                 OR h.situacao_historico IN ('cursando', 'trancada')))
        OR (m.status_matricula = 'ativa'   AND h.situacao_historico <> 'cursando')
        OR (m.status_matricula = 'trancada' AND h.situacao_historico <> 'trancada');
    IF violacoes > 0 THEN
        RAISE EXCEPTION 'carga: % histórico(s) incoerente(s) com o status da matrícula', violacoes;
    END IF;

    RAISE NOTICE 'carga ok: % alunos, % turmas, % matrículas', n_alunos, n_turmas, n_matriculas;
END
$$;

COMMIT;

-- Estatísticas atualizadas para o planejador (úteis para os EXPLAIN do Marco 2).
ANALYZE;
