-- =====================================================================
-- 06_views.sql
-- 3 views (oferta, vagas, histórico) + 1 materialized view de indicadores
-- Frente: Administração e Operação
-- Banco de Dados II (CCO072) — IESB 2026/2
-- =====================================================================
--
-- TODO: política de atualização da materialized view precisa estar
-- justificada (REFRESH manual? trigger? cron?).
